# Using Tensorflow as Numpy

## Tensors and Operations

#### Tensors

In [5]:
import tensorflow as tf

t=tf.constant([[1,2,3],[4,5,6]])
t

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [6]:
t.shape

TensorShape([2, 3])

In [7]:
t.dtype

tf.int32

In [8]:
t.numpy()

array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)

In [9]:
t[:,:2]

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [4, 5]], dtype=int32)>

In [10]:
t[...,2,tf.newaxis]

<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[3],
       [6]], dtype=int32)>

#### ops

In [12]:
t+10

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[11, 12, 13],
       [14, 15, 16]], dtype=int32)>

In [13]:
tf.square(t)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 1,  4,  9],
       [16, 25, 36]], dtype=int32)>

In [14]:
t @ tf.transpose(t)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[14, 32],
       [32, 77]], dtype=int32)>

In [15]:
tf.constant(3)

<tf.Tensor: shape=(), dtype=int32, numpy=3>

#### Keras low level API

In [17]:
K=tf.keras.backend

K.square(K.transpose(t)) + 10

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[11, 26],
       [14, 35],
       [19, 46]], dtype=int32)>

In [18]:
tf.square(tf.transpose(t)) + 10

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[11, 26],
       [14, 35],
       [19, 46]], dtype=int32)>

#### Tensors and Numpy

In [20]:
tf.reduce_sum([1,2,4])


<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [21]:
import numpy as np

a=np.array([1.,2.,3.,4.])
tf.constant(a,dtype=tf.float32)

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([1., 2., 3., 4.], dtype=float32)>

In [22]:
np.array(t)

array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)

In [23]:
tf.square(a)

<tf.Tensor: shape=(4,), dtype=float64, numpy=array([ 1.,  4.,  9., 16.])>

In [24]:
np.square(t)

array([[ 1,  4,  9],
       [16, 25, 36]], dtype=int32)

#### Type conversions

In [26]:
try:
    tf.constant(2.0)+tf.constant(10)
except tf.errors.InvalidArgumentError as ex:
    print(ex)



cannot compute AddV2 as input #1(zero-based) was expected to be a float tensor but is a int32 tensor [Op:AddV2] name: 


In [27]:
try:
    tf.constant(2.0) +tf.constant(10.0,dtype=tf.float64)
except tf.errors.InvalidArgumentError as ex:
    print(ex)

cannot compute AddV2 as input #1(zero-based) was expected to be a float tensor but is a double tensor [Op:AddV2] name: 


In [28]:
t2=tf.constant(30,dtype=tf.float64)

tf.constant(5.0)+ tf.cast(t2,tf.float32)

<tf.Tensor: shape=(), dtype=float32, numpy=35.0>

#### Variables

In [30]:
v=tf.Variable([[1,2,3],[4,5,6]])
v

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [31]:
v.assign(v*2)

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=int32, numpy=
array([[ 2,  4,  6],
       [ 8, 10, 12]], dtype=int32)>

In [32]:
v[0,2].assign(33)

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=int32, numpy=
array([[ 2,  4, 33],
       [ 8, 10, 12]], dtype=int32)>

In [33]:
v[:,2].assign([0,9])

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=int32, numpy=
array([[ 2,  4,  0],
       [ 8, 10,  9]], dtype=int32)>

In [34]:
v.scatter_nd_update(
    indices=[[0,0],[1,2]],updates=[200,200]
)

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=int32, numpy=
array([[200,   4,   0],
       [  8,  10, 200]], dtype=int32)>

In [35]:
sparse_delta=tf.IndexedSlices(values=[[1,1,1],[2,2,2]],
                             indices=[1,0])
v.scatter_update(sparse_delta)


<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=int32, numpy=
array([[2, 2, 2],
       [1, 1, 1]], dtype=int32)>

In [36]:
try:
    v[1]=[2,2,2]
except TypeError as ex:
    print(ex)

'ResourceVariable' object does not support item assignment


#### Strings

In [38]:
tf.constant(b"hello")

<tf.Tensor: shape=(), dtype=string, numpy=b'hello'>

In [39]:
tf.constant("café")

<tf.Tensor: shape=(), dtype=string, numpy=b'caf\xc3\xa9'>

In [40]:
u=tf.constant([ord(c) for c in "café"])
u

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 99,  97, 102, 233], dtype=int32)>

In [41]:
b=tf.strings.unicode_encode(u,"UTF-8")
tf.strings.length(b, unit="UTF8_CHAR")

<tf.Tensor: shape=(), dtype=int32, numpy=4>

In [42]:
tf.strings.unicode_decode(b,"UTF-8")

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 99,  97, 102, 233], dtype=int32)>

In [43]:
p=tf.constant(["Café", "Coffee", "caffè", "चाय"])
tf.strings.length(p, unit="UTF8_CHAR")

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([4, 6, 5, 3], dtype=int32)>

In [44]:
r=tf.strings.unicode_decode(p,"UTF-8")
r

<tf.RaggedTensor [[67, 97, 102, 233], [67, 111, 102, 102, 101, 101],
 [99, 97, 102, 102, 232], [2330, 2366, 2351]]>

#### Ragged Tensors

In [46]:
r=tf.ragged.constant([[2,4,5,7],[6,7],[],[7,5,2]])
r

<tf.RaggedTensor [[2, 4, 5, 7], [6, 7], [], [7, 5, 2]]>

In [47]:
r.to_tensor()

<tf.Tensor: shape=(4, 4), dtype=int32, numpy=
array([[2, 4, 5, 7],
       [6, 7, 0, 0],
       [0, 0, 0, 0],
       [7, 5, 2, 0]], dtype=int32)>

# Customizing Models and Training Algorithms

## Custom Loss Function

In [50]:
def huber_fn(y_true,y_pred):
    error=y_true - y_pred
    is_small_error = tf.abs(error) < 1
    square_loss= tf.square(error)/2
    linear_loss= tf.abs(error) - 0.5
    return tf.where(is_small_error,square_loss,linear_loss)

In [51]:
from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

housing=fetch_california_housing()
X_train_full,X_test,y_train_full,y_test=train_test_split(housing.data,housing.target.reshape(-1,1),
                                                        random_state=42)
X_train,X_valid,y_train,y_valid=train_test_split(X_train_full,y_train_full,random_state=42)

input_shape=X_train.shape[1:]

scaler=StandardScaler()
X_train_scaled=scaler.fit_transform(X_train)
X_valid_scaled=scaler.transform(X_valid)
X_test_scaled=scaler.transform(X_test)

tf.keras.utils.set_random_seed(42)

model=tf.keras.Sequential([
    tf.keras.layers.InputLayer(shape=input_shape),
    tf.keras.layers.Dense(25,activation="relu",kernel_initializer="he_normal"),
    tf.keras.layers.Dense(1)
])


In [52]:
model.compile(loss=huber_fn,
             optimizer="nadam",
             metrics=["mae"])

model.fit(X_train_scaled,y_train,
         epochs=5,
         validation_data=(X_valid_scaled,y_valid))

Epoch 1/5
363/363 ━━━━━━━━━━━━━━━━━━━━ 1s 679us/step - loss: 0.9556 - mae: 1.3617 - val_loss: 0.3932 - val_mae: 0.7026
Epoch 2/5
363/363 ━━━━━━━━━━━━━━━━━━━━ 0s 515us/step - loss: 0.2612 - mae: 0.5683 - val_loss: 0.2669 - val_mae: 0.5535
Epoch 3/5
363/363 ━━━━━━━━━━━━━━━━━━━━ 0s 516us/step - loss: 0.2177 - mae: 0.5095 - val_loss: 0.2225 - val_mae: 0.5021
Epoch 4/5
363/363 ━━━━━━━━━━━━━━━━━━━━ 0s 517us/step - loss: 0.2007 - mae: 0.4861 - val_loss: 0.1999 - val_mae: 0.4755
Epoch 5/5
363/363 ━━━━━━━━━━━━━━━━━━━━ 0s 515us/step - loss: 0.1912 - mae: 0.4724 - val_loss: 0.1843 - val_mae: 0.4573


## Storing and Loading Models With Custom Objects

In [54]:
model.save("my_custom_loss_fn_model.keras")

In [55]:
model=tf.keras.models.load_model("my_custom_loss_fn_model.keras",
                                custom_objects={"huber_fn":huber_fn})

In [56]:
model.fit(X_train_scaled,y_train,
         epochs=4,
         validation_data=(X_valid_scaled,y_valid))

Epoch 1/4
363/363 ━━━━━━━━━━━━━━━━━━━━ 1s 674us/step - loss: 0.1850 - mae: 0.4632 - val_loss: 0.1751 - val_mae: 0.4463
Epoch 2/4
363/363 ━━━━━━━━━━━━━━━━━━━━ 0s 520us/step - loss: 0.1809 - mae: 0.4572 - val_loss: 0.1696 - val_mae: 0.4393
Epoch 3/4
363/363 ━━━━━━━━━━━━━━━━━━━━ 0s 519us/step - loss: 0.1781 - mae: 0.4530 - val_loss: 0.1656 - val_mae: 0.4341
Epoch 4/4
363/363 ━━━━━━━━━━━━━━━━━━━━ 0s 519us/step - loss: 0.1759 - mae: 0.4496 - val_loss: 0.1622 - val_mae: 0.4296


In [57]:
def create_huber(threshold=1.0):
    def huber_fn(y_true,y_pred):
        error= y_true-y_pred
        is_small_error= tf.abs(error)< threshold
        squared_loss= tf.square(error)/2
        linear_loss= threshold*tf.abs(error) - threshold**2 / 2
        return tf.where(is_small_error,squared_loss,linear_loss)
    return huber_fn

In [58]:
model.compile(loss=create_huber(1.8),optimizer="nadam",metrics=["mae"])

In [59]:
model.fit(X_train_scaled,y_train,
         epochs=4,
         validation_data=(X_valid_scaled,y_valid))

Epoch 1/4
363/363 ━━━━━━━━━━━━━━━━━━━━ 1s 676us/step - loss: 0.1940 - mae: 0.4490 - val_loss: 0.1835 - val_mae: 0.4323
Epoch 2/4
363/363 ━━━━━━━━━━━━━━━━━━━━ 0s 519us/step - loss: 0.1918 - mae: 0.4462 - val_loss: 0.1745 - val_mae: 0.4261
Epoch 3/4
363/363 ━━━━━━━━━━━━━━━━━━━━ 0s 521us/step - loss: 0.1904 - mae: 0.4443 - val_loss: 0.1795 - val_mae: 0.4286
Epoch 4/4
363/363 ━━━━━━━━━━━━━━━━━━━━ 0s 523us/step - loss: 0.1893 - mae: 0.4427 - val_loss: 0.1814 - val_mae: 0.4290


In [60]:
model.save("my_custom_loss_threshold_model.keras")

In [61]:
model=tf.keras.models.load_model("my_custom_loss_threshold_model.keras",
                                custom_objects={"huber_fn":create_huber(1.8)})

In [62]:
model.fit(X_train_scaled,y_train,
         epochs=2,
         validation_data=(X_valid_scaled,y_valid))

Epoch 1/2
363/363 ━━━━━━━━━━━━━━━━━━━━ 0s 678us/step - loss: 0.1881 - mae: 0.4410 - val_loss: 0.1730 - val_mae: 0.4231
Epoch 2/2
363/363 ━━━━━━━━━━━━━━━━━━━━ 0s 521us/step - loss: 0.1872 - mae: 0.4396 - val_loss: 0.1817 - val_mae: 0.4279


In [63]:
class HuberLoss(tf.keras.losses.Loss):
    def __init__(self,threshold=1.0,**kwargs):
        self.threshold=threshold
        super().__init__(**kwargs)
        
    def call(self,y_true,y_pred):
        error= y_true - y_pred
        is_small_error= tf.abs(error) < self.threshold
        square_loss= tf.square(error) /2
        linear_loss= self.threshold * tf.abs(error) - self.threshold**2 / 2
        return tf.where(is_small_error,square_loss,linear_loss)

    def get_config(self):
        base_config=super().get_config()
        return {**base_config,"threshold":self.threshold}

In [64]:
tf.keras.utils.set_random_seed(42)

model=tf.keras.Sequential([
    tf.keras.layers.InputLayer(shape=input_shape),
    tf.keras.layers.Dense(30,activation="relu",
                         kernel_initializer="he_normal"),
    tf.keras.layers.Dense(1)
])


In [65]:
model.compile(loss=HuberLoss(1.4),optimizer="nadam",metrics=["mae"])

In [66]:
model.fit(X_train_scaled,y_train,
         epochs=3,
         validation_data=(X_valid_scaled,y_valid))

Epoch 1/3
363/363 ━━━━━━━━━━━━━━━━━━━━ 1s 678us/step - loss: 0.9035 - mae: 1.1389 - val_loss: 0.4178 - val_mae: 0.6595
Epoch 2/3
363/363 ━━━━━━━━━━━━━━━━━━━━ 0s 521us/step - loss: 0.2919 - mae: 0.5737 - val_loss: 0.2988 - val_mae: 0.5456
Epoch 3/3
363/363 ━━━━━━━━━━━━━━━━━━━━ 0s 518us/step - loss: 0.2429 - mae: 0.5161 - val_loss: 0.2395 - val_mae: 0.4911


In [67]:
model.save("my_custom_loss_threshold_class_model.keras")

In [68]:
model=tf.keras.models.load_model("my_custom_loss_threshold_class_model.keras",
                                custom_objects={"HuberLoss":HuberLoss})

In [69]:
model.fit(X_train_scaled,y_train,
         epochs=3,
          validation_data=(X_valid_scaled,y_valid)
         )

Epoch 1/3
363/363 ━━━━━━━━━━━━━━━━━━━━ 0s 678us/step - loss: 0.2189 - mae: 0.4864 - val_loss: 0.2084 - val_mae: 0.4635
Epoch 2/3
363/363 ━━━━━━━━━━━━━━━━━━━━ 0s 525us/step - loss: 0.2063 - mae: 0.4703 - val_loss: 0.1820 - val_mae: 0.4415
Epoch 3/3
363/363 ━━━━━━━━━━━━━━━━━━━━ 0s 519us/step - loss: 0.1988 - mae: 0.4611 - val_loss: 0.1821 - val_mae: 0.4395


In [70]:
model.loss.threshold

1.4

## Other Custom Functions

In [72]:
def my_softplus(z):
    return tf.math.log(1+tf.exp(z))

def my_glorot_initializer(shape,dtype=tf.float32):
    stddev= tf.sqrt(2 / (shape[0] + shape[1]))
    
    return tf.random.normal(shape,stddev=stddev,dtype=dtype)

def my_l1_regu(weights):
    return 0.01 * tf.reduce_sum(tf.abs(weights))

def my_positive_weights(weights):
    return tf.where(weights<0. ,tf.zeros_like(weights),weights)

In [73]:
class MyL1Regularizer(tf.keras.regularizers.Regularizer):
    def __init__(self, factor):
        self.factor = factor

    def __call__(self, weights):
        return self.factor * tf.reduce_sum(tf.abs(weights))

    def get_config(self):
        return {"factor": self.factor}


In [74]:
class MyPositiveWeights(tf.keras.constraints.Constraint):
    def __init__(self):
        pass
    def __call__(self,weights):
        return tf.where(weights<0. ,tf.zeros_like(weights),weights)
    def get_config(self):
        return {}
    

In [75]:
tf.keras.utils.set_random_seed(42)

model=tf.keras.Sequential([
    tf.keras.layers.InputLayer(shape=input_shape),
    tf.keras.layers.Dense(30,activation=my_softplus,
                          kernel_initializer=my_glorot_initializer,
                          kernel_regularizer=MyL1Regularizer(factor=0.01),
                          kernel_constraint=MyPositiveWeights()
                           ),
                         
    tf.keras.layers.Dense(1)
])
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_4 (Dense)                 │ (None, 30)             │           270 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 1)              │            31 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 301 (1.18 KB)

 Trainable params: 301 (1.18 KB)

 Non-trainable params: 0 (0.00 B)

In [76]:
model.compile(loss=HuberLoss(1.2),optimizer="nadam",metrics=["mae"])

In [77]:
history=model.fit(X_train_scaled,y_train,
                 epochs=4,
                 validation_data=(X_valid_scaled,y_valid))

Epoch 1/4
363/363 ━━━━━━━━━━━━━━━━━━━━ 1s 708us/step - loss: 1.1080 - mae: 1.2316 - val_loss: inf - val_mae: inf
Epoch 2/4
363/363 ━━━━━━━━━━━━━━━━━━━━ 0s 545us/step - loss: 0.4222 - mae: 0.6201 - val_loss: inf - val_mae: inf
Epoch 3/4
363/363 ━━━━━━━━━━━━━━━━━━━━ 0s 541us/step - loss: 0.3799 - mae: 0.6103 - val_loss: inf - val_mae: inf
Epoch 4/4
363/363 ━━━━━━━━━━━━━━━━━━━━ 0s 539us/step - loss: 0.3623 - mae: 0.6105 - val_loss: 0.3385 - val_mae: 0.5923


## Custom Metrics

In [79]:
tf.keras.utils.set_random_seed(42)
model=tf.keras.Sequential([
    tf.keras.layers.InputLayer(shape=input_shape),
    tf.keras.layers.Dense(30,activation="relu",
                         kernel_initializer="he_normal"),
    tf.keras.layers.Dense(1)
])

In [80]:
model.compile(loss="mse",optimizer="nadam",metrics=[HuberLoss(2)])

In [81]:
model.fit(X_train_scaled,y_train,
         epochs=3,
         validation_data=(X_valid_scaled,y_valid))

Epoch 1/3
363/363 ━━━━━━━━━━━━━━━━━━━━ 1s 683us/step - huber_loss_2: 1.0788 - loss: 2.5942 - val_huber_loss_2: 0.5646 - val_loss: 21.3898
Epoch 2/3
363/363 ━━━━━━━━━━━━━━━━━━━━ 0s 524us/step - huber_loss_2: 0.3403 - loss: 0.7644 - val_huber_loss_2: 0.4281 - val_loss: 11.2129
Epoch 3/3
363/363 ━━━━━━━━━━━━━━━━━━━━ 0s 522us/step - huber_loss_2: 0.2803 - loss: 0.6047 - val_huber_loss_2: 0.3411 - val_loss: 5.6292


In [82]:
tf.keras.utils.set_random_seed(42)
model=tf.keras.Sequential([
    tf.keras.layers.InputLayer(shape=input_shape),
    tf.keras.layers.Dense(30,activation="relu",
                         kernel_initializer="he_normal"),
    tf.keras.layers.Dense(1)
])

In [83]:
model.compile(loss="mse",optimizer="nadam",metrics=[create_huber(2)])

In [84]:
model.fit(X_train_scaled,y_train,
         epochs=3,
         validation_data=(X_valid_scaled,y_valid))

Epoch 1/3
363/363 ━━━━━━━━━━━━━━━━━━━━ 1s 676us/step - huber_fn: 1.0788 - loss: 2.5942 - val_huber_fn: 0.5648 - val_loss: 21.3898
Epoch 2/3
363/363 ━━━━━━━━━━━━━━━━━━━━ 0s 518us/step - huber_fn: 0.3403 - loss: 0.7644 - val_huber_fn: 0.4283 - val_loss: 11.2129
Epoch 3/3
363/363 ━━━━━━━━━━━━━━━━━━━━ 0s 517us/step - huber_fn: 0.2803 - loss: 0.6047 - val_huber_fn: 0.3412 - val_loss: 5.6292


In [85]:
model.compile(loss=create_huber(2),optimizer="nadam",metrics=[create_huber(2)])

In [86]:
model.fit(X_train_scaled,y_train,
         epochs=3,
         validation_data=(X_valid_scaled,y_valid))


Epoch 1/3
363/363 ━━━━━━━━━━━━━━━━━━━━ 1s 679us/step - huber_fn: 0.2443 - loss: 0.2443 - val_huber_fn: 0.2984 - val_loss: 0.2984
Epoch 2/3
363/363 ━━━━━━━━━━━━━━━━━━━━ 0s 521us/step - huber_fn: 0.2206 - loss: 0.2206 - val_huber_fn: 0.2439 - val_loss: 0.2439
Epoch 3/3
363/363 ━━━━━━━━━━━━━━━━━━━━ 0s 520us/step - huber_fn: 0.2101 - loss: 0.2101 - val_huber_fn: 0.2090 - val_loss: 0.2090


### Streaming Metrics

In [88]:
precision=tf.keras.metrics.Precision()

In [89]:
precision([0, 1, 1, 1, 0, 1, 0, 1], [1, 1, 0, 1, 0, 1, 0, 1]) # precision = 4 / 5 = 0.8

<tf.Tensor: shape=(), dtype=float32, numpy=0.800000011920929>

In [90]:
precision([0, 1, 0, 0, 1, 0, 1, 1], [1, 0, 1, 1, 0, 0, 0, 0]) #precision=0/3=0 

<tf.Tensor: shape=(), dtype=float32, numpy=0.5>

In [91]:
precision.result()   #Final result-> 4/(5+3)=0.5

<tf.Tensor: shape=(), dtype=float32, numpy=0.5>

In [92]:
precision.variables

[<Variable path=precision/true_positives, shape=(1,), dtype=float32, value=[4.]>,
 <Variable path=precision/false_positives, shape=(1,), dtype=float32, value=[4.]>]

In [93]:
precision.reset_state()

In [94]:
precision.result()

<tf.Tensor: shape=(), dtype=float32, numpy=0.0>

In [95]:
class HuberMetric(tf.keras.metrics.Metric):
    def __init__(self,threshold=1.0,**kwargs):
        super().__init__(**kwargs)
        self.threshold=threshold
        self.huber_fn=create_huber(threshold)
        self.total=self.add_weight(name="total",initializer="zeros") #Ek TensorFlow variable banao jiska naam total ho aur shuru mein value 0.0 ho.
        self.count=self.add_weight(name="count",initializer="zeros")

    def update_state(self,y_true,y_pred,sample_weight=None):
        sample_metrics=self.huber_fn(y_true,y_pred)
        self.total.assign_add(tf.reduce_sum(sample_metrics))
        self.count.assign_add(tf.cast(tf.size(y_true),tf.float32))

    def result(self):
        return self.total/self.count

    def get_config(self):
        base_config=super().get_config()
        return {**base_config,"threshold":self.threshold}

In [96]:
m=HuberMetric(3.0)

m(tf.constant([[3.]]),tf.constant([[12.]]))

#error->12-3=9
#9>3 so linear loss
# total-> 3*9 - 3^2 /2 =22.5
# count=1
#result=22.5/1

<tf.Tensor: shape=(), dtype=float32, numpy=22.5>

In [97]:
m(tf.constant([[2.],[3.]]),tf.constant([[1.],[7.]]))

# total -> total + (|1-2|²)/2 + 3*|7-3|-3²/2= 22.5+8=30.5
#Count -> count + 2 =1+2=3
#result= 30.5/3=10.1666

<tf.Tensor: shape=(), dtype=float32, numpy=10.166666984558105>

In [98]:
m.result()

<tf.Tensor: shape=(), dtype=float32, numpy=10.166666984558105>

In [99]:
m.variables

[<Variable path=huber_metric/total, shape=(), dtype=float32, value=30.5>,
 <Variable path=huber_metric/count, shape=(), dtype=float32, value=3.0>]

In [100]:
m.reset_state()

In [101]:
m.variables

[<Variable path=huber_metric/total, shape=(), dtype=float32, value=0.0>,
 <Variable path=huber_metric/count, shape=(), dtype=float32, value=0.0>]

In [102]:
tf.keras.utils.set_random_seed(42)

model=tf.keras.Sequential([
    tf.keras.layers.InputLayer(shape=input_shape),
    tf.keras.layers.Dense(30,activation="relu",
                         kernel_initializer="he_normal"),
    tf.keras.layers.Dense(1)
])

In [103]:
model.compile(loss=HuberLoss(2),
             optimizer="nadam",
             metrics=[HuberMetric(2)])

In [104]:
model.fit(X_train_scaled,y_train,
         epochs=4,
         validation_data=(X_valid_scaled,y_valid))

Epoch 1/4
363/363 ━━━━━━━━━━━━━━━━━━━━ 1s 681us/step - huber_metric_1: 1.0512 - loss: 1.0512 - val_huber_metric_1: 0.5086 - val_loss: 0.5086
Epoch 2/4
363/363 ━━━━━━━━━━━━━━━━━━━━ 0s 519us/step - huber_metric_1: 0.3170 - loss: 0.3170 - val_huber_metric_1: 0.3527 - val_loss: 0.3527
Epoch 3/4
363/363 ━━━━━━━━━━━━━━━━━━━━ 0s 521us/step - huber_metric_1: 0.2612 - loss: 0.2612 - val_huber_metric_1: 0.2689 - val_loss: 0.2689
Epoch 4/4
363/363 ━━━━━━━━━━━━━━━━━━━━ 0s 518us/step - huber_metric_1: 0.2328 - loss: 0.2328 - val_huber_metric_1: 0.2207 - val_loss: 0.2207


In [105]:
model.save("my_custom_huber_metric_model.keras")

In [106]:
model=tf.keras.models.load_model("my_custom_huber_metric_model.keras",
                                custom_objects={"HuberLoss":HuberLoss,
                                               "HuberMetric":HuberMetric})

In [107]:
model.fit(X_train_scaled,y_train,
         epochs=3,
         validation_data=(X_valid_scaled,y_valid))

Epoch 1/3
363/363 ━━━━━━━━━━━━━━━━━━━━ 0s 668us/step - huber_metric_1: 0.2178 - loss: 0.2178 - val_huber_metric_1: 0.1899 - val_loss: 0.1899
Epoch 2/3
363/363 ━━━━━━━━━━━━━━━━━━━━ 0s 519us/step - huber_metric_1: 0.2093 - loss: 0.2093 - val_huber_metric_1: 0.1996 - val_loss: 0.1996
Epoch 3/3
363/363 ━━━━━━━━━━━━━━━━━━━━ 0s 517us/step - huber_metric_1: 0.2036 - loss: 0.2036 - val_huber_metric_1: 0.2243 - val_loss: 0.2243


In [108]:
class HuberMetric(tf.keras.metrics.Mean):
    def __init__(self,threshold=1.0,name="HuberMetric",dtype=None):
        self.threshold=threshold
        self.huber_fn=create_huber(threshold)
        super().__init__(name=name,dtype=dtype)

    def update_state(self,y_true,y_pred,sample_weight=None):
        metric=self.huber_fn(y_true,y_pred)
        super(HuberMetric,self).update_state(metric,sample_weight)

    def get_config(self):
        base_config=super().get_config()
        return {**base_config,"threshold":self.threshold}

In [109]:
tf.keras.utils.set_random_seed(42)

model=tf.keras.Sequential([
    tf.keras.layers.InputLayer(shape=input_shape),
    tf.keras.layers.Dense(30,activation="relu",
                         kernel_initializer="he_normal"),
    tf.keras.layers.Dense(1)
])

In [110]:
model.compile(loss=HuberLoss(2),
             optimizer="nadam",
                 weighted_metrics=[HuberMetric(2)])

In [111]:
np.random.seed(42)
sample_weights=np.random.rand(len(y_train))
model.fit(X_train_scaled,y_train,
         epochs=4,
         sample_weight=sample_weights,
         validation_data=(X_valid_scaled,y_valid))

Epoch 1/4
363/363 ━━━━━━━━━━━━━━━━━━━━ 1s 692us/step - HuberMetric: 1.0599 - loss: 0.5274 - val_HuberMetric: 0.5222 - val_loss: 0.5222
Epoch 2/4
363/363 ━━━━━━━━━━━━━━━━━━━━ 0s 522us/step - HuberMetric: 0.3215 - loss: 0.1598 - val_HuberMetric: 0.3468 - val_loss: 0.3468
Epoch 3/4
363/363 ━━━━━━━━━━━━━━━━━━━━ 0s 526us/step - HuberMetric: 0.2647 - loss: 0.1316 - val_HuberMetric: 0.2743 - val_loss: 0.2743
Epoch 4/4
363/363 ━━━━━━━━━━━━━━━━━━━━ 0s 533us/step - HuberMetric: 0.2371 - loss: 0.1178 - val_HuberMetric: 0.2428 - val_loss: 0.2428


In [112]:
model.save("my_custom_huber_metric_model_v2.keras")

In [113]:
model=tf.keras.models.load_model("my_custom_huber_metric_model.keras",
                                custom_objects={"HuberLoss":HuberLoss,
                                               "HuberMetric":HuberMetric})

In [114]:
model.fit(X_train_scaled,y_train,
         epochs=2)

Epoch 1/2
363/363 ━━━━━━━━━━━━━━━━━━━━ 0s 397us/step - huber_metric_1: 0.2178 - loss: 0.2178 
Epoch 2/2
363/363 ━━━━━━━━━━━━━━━━━━━━ 0s 395us/step - huber_metric_1: 0.2093 - loss: 0.2093


## Custom Layers

In [116]:
exp_layer=tf.keras.layers.Lambda(lambda x:tf.exp(x))

In [117]:
exp_layer(tf.constant([-2.,3.,5.]))

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1.3533528e-01, 2.0085537e+01, 1.4841316e+02], dtype=float32)>

In [118]:
tf.keras.utils.set_random_seed(42)

model=tf.keras.Sequential([
    tf.keras.layers.InputLayer(shape=input_shape),
    tf.keras.layers.Dense(30,activation="relu"),
    tf.keras.layers.Dense(1),
    exp_layer
])

In [119]:
model.compile(loss="mse",optimizer="sgd",metrics=[HuberLoss(2.0)])

In [120]:
model.fit(X_train_scaled,y_train,
         epochs=2)

Epoch 1/2
363/363 ━━━━━━━━━━━━━━━━━━━━ 0s 364us/step - huber_loss_5: 0.5644 - loss: 1.2350 
Epoch 2/2
363/363 ━━━━━━━━━━━━━━━━━━━━ 0s 349us/step - huber_loss_5: 0.2871 - loss: 0.6130


In [121]:
class MyDense(tf.keras.layers.Layer):
    def __init__(self,units,activation=None,**kwargs):
        super().__init__(**kwargs)
        self.units=units
        self.activation=tf.keras.activations.get(activation)

    def build(self,batch_input_size):
        self.kernel=self.add_weight(
            name="kernel",
            initializer="he_normal",
            shape=[batch_input_size[-1],self.units]
        )
        self.bias=self.add_weight(
            name="bias",
            shape=[self.units],
            initializer="zeros"
        )
        
    def call(self,X):
        return self.activation(X@self.kernel + self.bias)

    def get_config(self):
        base_config=super().get_config()
        return {**base_config,"units":self.units,
               "activation":tf.keras.activations.serialize(self.activation)} #Converts function to string name for saving


In [122]:
tf.keras.utils.set_random_seed(42)
model = tf.keras.Sequential([
    tf.keras.layers.InputLayer(shape=input_shape),
    MyDense(30, activation="relu"),
    MyDense(1)
])
model.compile(loss="mse", optimizer="nadam")
model.fit(X_train_scaled, y_train, epochs=2,
          validation_data=(X_valid_scaled, y_valid))

Epoch 1/2
363/363 ━━━━━━━━━━━━━━━━━━━━ 0s 613us/step - loss: 5.7265 - val_loss: 6.9255
Epoch 2/2
363/363 ━━━━━━━━━━━━━━━━━━━━ 0s 488us/step - loss: 0.9550 - val_loss: 2.6011


In [123]:
model.evaluate(X_test_scaled,y_test)

162/162 ━━━━━━━━━━━━━━━━━━━━ 0s 312us/step - loss: 0.7227


0.7036542296409607

In [124]:
model.save("my_custom_layer_model.keras")

In [125]:
model=tf.keras.models.load_model("my_custom_layer_model.keras",
                                custom_objects={"MyDense":MyDense})

In [126]:
model.fit(X_train_scaled,y_train,
         epochs=2)

Epoch 1/2
363/363 ━━━━━━━━━━━━━━━━━━━━ 0s 374us/step - loss: 0.7034 
Epoch 2/2
363/363 ━━━━━━━━━━━━━━━━━━━━ 0s 365us/step - loss: 0.5803


In [127]:
class MyMultilayer(tf.keras.layers.Layer):
    def call(self,inputs):
        input1,input2=inputs
        added=input1+input2
        multiplied=input1*input2
        divided=input1/input2

        return [added,multiplied,divided]

In [128]:
input1=tf.keras.layers.Input(shape=[3])
input2=tf.keras.layers.Input(shape=[3])

MyMultilayer()((input1,input2))

[<KerasTensor shape=(None, 3), dtype=float32, sparse=False, ragged=False, name=keras_tensor_50>,
 <KerasTensor shape=(None, 3), dtype=float32, sparse=False, ragged=False, name=keras_tensor_51>,
 <KerasTensor shape=(None, 3), dtype=float32, sparse=False, ragged=False, name=keras_tensor_52>]

In [129]:
class MyGaussianNoise(tf.keras.layers.Layer):
    def __init__(self,stddev,**kwargs):
        super().__init__(**kwargs)
        self.stddev=stddev

    def call(self,X,training=None):
        if training:
            noise=tf.random.normal(tf.shape(X),stddev=self.stddev)
            return X+noise
        else:
            return X
        

In [ ]:
tf.keras.utils.set_random_seed(42)

model=tf.keras.Sequential([
    tf.keras.layers.InputLayer(shape=input_shape),
    MyGaussianNoise(stddev=1.0),
    tf.keras.layers.Dense(20,activation="relu",
                         kernel_initializer="he_normal"),
    tf.keras.layers.Dense(1)
])
model.compile(loss="mse",optimizer="nadam",metrics=[HuberMetric(1)])
model.fit(X_train_scaled,y_train,
         epochs=3,
         validation_data=(X_valid_scaled,y_valid))
model.evaluate(X_test_scaled,y_test)

Epoch 1/3
