# Using Tensorflow as Numpy

## Tensors and Operations

#### Tensors

In [4]:
import tensorflow as tf

t=tf.constant([[1,2,3],[4,5,6]])
t

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [5]:
t.shape

TensorShape([2, 3])

In [6]:
t.dtype

tf.int32

In [7]:
t.numpy()

array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)

In [8]:
t[:,:2]

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [4, 5]], dtype=int32)>

In [9]:
t[...,2,tf.newaxis]

<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[3],
       [6]], dtype=int32)>

#### ops

In [11]:
t+10

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[11, 12, 13],
       [14, 15, 16]], dtype=int32)>

In [12]:
tf.square(t)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 1,  4,  9],
       [16, 25, 36]], dtype=int32)>

In [13]:
t @ tf.transpose(t)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[14, 32],
       [32, 77]], dtype=int32)>

In [14]:
tf.constant(3)

<tf.Tensor: shape=(), dtype=int32, numpy=3>

#### Keras low level API

In [16]:
K=tf.keras.backend

K.square(K.transpose(t)) + 10

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[11, 26],
       [14, 35],
       [19, 46]], dtype=int32)>

In [17]:
tf.square(tf.transpose(t)) + 10

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[11, 26],
       [14, 35],
       [19, 46]], dtype=int32)>

#### Tensors and Numpy

In [19]:
tf.reduce_sum([1,2,4])


<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [20]:
import numpy as np

a=np.array([1.,2.,3.,4.])
tf.constant(a,dtype=tf.float32)

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([1., 2., 3., 4.], dtype=float32)>

In [21]:
np.array(t)

array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)

In [22]:
tf.square(a)

<tf.Tensor: shape=(4,), dtype=float64, numpy=array([ 1.,  4.,  9., 16.])>

In [23]:
np.square(t)

array([[ 1,  4,  9],
       [16, 25, 36]], dtype=int32)

#### Type conversions

In [25]:
try:
    tf.constant(2.0)+tf.constant(10)
except tf.errors.InvalidArgumentError as ex:
    print(ex)



cannot compute AddV2 as input #1(zero-based) was expected to be a float tensor but is a int32 tensor [Op:AddV2] name: 


In [26]:
try:
    tf.constant(2.0) +tf.constant(10.0,dtype=tf.float64)
except tf.errors.InvalidArgumentError as ex:
    print(ex)

cannot compute AddV2 as input #1(zero-based) was expected to be a float tensor but is a double tensor [Op:AddV2] name: 


In [27]:
t2=tf.constant(30,dtype=tf.float64)

tf.constant(5.0)+ tf.cast(t2,tf.float32)

<tf.Tensor: shape=(), dtype=float32, numpy=35.0>

#### Variables

In [29]:
v=tf.Variable([[1,2,3],[4,5,6]])
v

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [30]:
v.assign(v*2)

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=int32, numpy=
array([[ 2,  4,  6],
       [ 8, 10, 12]], dtype=int32)>

In [31]:
v[0,2].assign(33)

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=int32, numpy=
array([[ 2,  4, 33],
       [ 8, 10, 12]], dtype=int32)>

In [32]:
v[:,2].assign([0,9])

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=int32, numpy=
array([[ 2,  4,  0],
       [ 8, 10,  9]], dtype=int32)>

In [33]:
v.scatter_nd_update(
    indices=[[0,0],[1,2]],updates=[200,200]
)

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=int32, numpy=
array([[200,   4,   0],
       [  8,  10, 200]], dtype=int32)>

In [34]:
sparse_delta=tf.IndexedSlices(values=[[1,1,1],[2,2,2]],
                             indices=[1,0])
v.scatter_update(sparse_delta)


<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=int32, numpy=
array([[2, 2, 2],
       [1, 1, 1]], dtype=int32)>

In [35]:
try:
    v[1]=[2,2,2]
except TypeError as ex:
    print(ex)

'ResourceVariable' object does not support item assignment


#### Strings

In [37]:
tf.constant(b"hello")

<tf.Tensor: shape=(), dtype=string, numpy=b'hello'>

In [38]:
tf.constant("café")

<tf.Tensor: shape=(), dtype=string, numpy=b'caf\xc3\xa9'>

In [39]:
u=tf.constant([ord(c) for c in "café"])
u

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 99,  97, 102, 233], dtype=int32)>

In [40]:
b=tf.strings.unicode_encode(u,"UTF-8")
tf.strings.length(b, unit="UTF8_CHAR")

<tf.Tensor: shape=(), dtype=int32, numpy=4>

In [41]:
tf.strings.unicode_decode(b,"UTF-8")

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 99,  97, 102, 233], dtype=int32)>

In [42]:
p=tf.constant(["Café", "Coffee", "caffè", "चाय"])
tf.strings.length(p, unit="UTF8_CHAR")

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([4, 6, 5, 3], dtype=int32)>

In [43]:
r=tf.strings.unicode_decode(p,"UTF-8")
r

<tf.RaggedTensor [[67, 97, 102, 233], [67, 111, 102, 102, 101, 101],
 [99, 97, 102, 102, 232], [2330, 2366, 2351]]>

#### Ragged Tensors

In [45]:
r=tf.ragged.constant([[2,4,5,7],[6,7],[],[7,5,2]])
r

<tf.RaggedTensor [[2, 4, 5, 7], [6, 7], [], [7, 5, 2]]>

In [46]:
r.to_tensor()

<tf.Tensor: shape=(4, 4), dtype=int32, numpy=
array([[2, 4, 5, 7],
       [6, 7, 0, 0],
       [0, 0, 0, 0],
       [7, 5, 2, 0]], dtype=int32)>

# Customizing Models and Training Algorithms

## Custom Loss Function

In [49]:
def huber_fn(y_true,y_pred):
    error=y_true - y_pred
    is_small_error = tf.abs(error) < 1
    square_loss= tf.square(error)/2
    linear_loss= tf.abs(error) - 0.5
    return tf.where(is_small_error,square_loss,linear_loss)

In [50]:
from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

housing=fetch_california_housing()
X_train_full,X_test,y_train_full,y_test=train_test_split(housing.data,housing.target.reshape(-1,1),
                                                        random_state=42)
X_train,X_valid,y_train,y_valid=train_test_split(X_train_full,y_train_full,random_state=42)

input_shape=X_train.shape[1:]

scaler=StandardScaler()
X_train_scaled=scaler.fit_transform(X_train)
X_valid_scaled=scaler.transform(X_valid)
X_test_scaled=scaler.transform(X_test)

tf.keras.utils.set_random_seed(42)

model=tf.keras.Sequential([
    tf.keras.layers.InputLayer(shape=input_shape),
    tf.keras.layers.Dense(25,activation="relu",kernel_initializer="he_normal"),
    tf.keras.layers.Dense(1)
])


In [51]:
model.compile(loss=huber_fn,
             optimizer="nadam",
             metrics=["mae"])

model.fit(X_train_scaled,y_train,
         epochs=5,
         validation_data=(X_valid_scaled,y_valid))

Epoch 1/5
363/363 ━━━━━━━━━━━━━━━━━━━━ 1s 675us/step - loss: 0.9556 - mae: 1.3617 - val_loss: 0.3932 - val_mae: 0.7026
Epoch 2/5
363/363 ━━━━━━━━━━━━━━━━━━━━ 0s 519us/step - loss: 0.2612 - mae: 0.5683 - val_loss: 0.2669 - val_mae: 0.5535
Epoch 3/5
363/363 ━━━━━━━━━━━━━━━━━━━━ 0s 516us/step - loss: 0.2177 - mae: 0.5095 - val_loss: 0.2225 - val_mae: 0.5021
Epoch 4/5
363/363 ━━━━━━━━━━━━━━━━━━━━ 0s 517us/step - loss: 0.2007 - mae: 0.4861 - val_loss: 0.1999 - val_mae: 0.4755
Epoch 5/5
363/363 ━━━━━━━━━━━━━━━━━━━━ 0s 522us/step - loss: 0.1912 - mae: 0.4724 - val_loss: 0.1843 - val_mae: 0.4573


## Storing and Loading Models With Custom Objects

In [53]:
model.save("my_custom_loss_fn_model.keras")

In [54]:
model=tf.keras.models.load_model("my_custom_loss_fn_model.keras",
                                custom_objects={"huber_fn":huber_fn})

In [55]:
model.fit(X_train_scaled,y_train,
         epochs=4,
         validation_data=(X_valid_scaled,y_valid))

Epoch 1/4
363/363 ━━━━━━━━━━━━━━━━━━━━ 0s 674us/step - loss: 0.1850 - mae: 0.4632 - val_loss: 0.1751 - val_mae: 0.4463
Epoch 2/4
363/363 ━━━━━━━━━━━━━━━━━━━━ 0s 520us/step - loss: 0.1809 - mae: 0.4572 - val_loss: 0.1696 - val_mae: 0.4393
Epoch 3/4
363/363 ━━━━━━━━━━━━━━━━━━━━ 0s 726us/step - loss: 0.1781 - mae: 0.4530 - val_loss: 0.1656 - val_mae: 0.4341
Epoch 4/4
363/363 ━━━━━━━━━━━━━━━━━━━━ 0s 518us/step - loss: 0.1759 - mae: 0.4496 - val_loss: 0.1622 - val_mae: 0.4296


In [56]:
def create_huber(threshold=1.0):
    def huber_fn(y_true,y_pred):
        error= y_true-y_pred
        is_small_error= tf.abs(error)< threshold
        squared_loss= tf.square(error)/2
        linear_loss= threshold*tf.abs(error) - threshold**2 / 2
        return tf.where(is_small_error,squared_loss,linear_loss)
    return huber_fn

In [57]:
model.compile(loss=create_huber(1.8),optimizer="nadam",metrics=["mae"])

In [58]:
model.fit(X_train_scaled,y_train,
         epochs=4,
         validation_data=(X_valid_scaled,y_valid))

Epoch 1/4
363/363 ━━━━━━━━━━━━━━━━━━━━ 1s 673us/step - loss: 0.1940 - mae: 0.4490 - val_loss: 0.1835 - val_mae: 0.4323
Epoch 2/4
363/363 ━━━━━━━━━━━━━━━━━━━━ 0s 521us/step - loss: 0.1918 - mae: 0.4462 - val_loss: 0.1745 - val_mae: 0.4261
Epoch 3/4
363/363 ━━━━━━━━━━━━━━━━━━━━ 0s 520us/step - loss: 0.1904 - mae: 0.4443 - val_loss: 0.1795 - val_mae: 0.4286
Epoch 4/4
363/363 ━━━━━━━━━━━━━━━━━━━━ 0s 520us/step - loss: 0.1893 - mae: 0.4427 - val_loss: 0.1814 - val_mae: 0.4290


In [59]:
model.save("my_custom_loss_threshold_model.keras")

In [60]:
model=tf.keras.models.load_model("my_custom_loss_threshold_model.keras",
                                custom_objects={"huber_fn":create_huber(1.8)})

In [61]:
model.fit(X_train_scaled,y_train,
         epochs=2,
         validation_data=(X_valid_scaled,y_valid))

Epoch 1/2
363/363 ━━━━━━━━━━━━━━━━━━━━ 0s 677us/step - loss: 0.1881 - mae: 0.4410 - val_loss: 0.1730 - val_mae: 0.4231
Epoch 2/2
363/363 ━━━━━━━━━━━━━━━━━━━━ 0s 519us/step - loss: 0.1872 - mae: 0.4396 - val_loss: 0.1817 - val_mae: 0.4279


In [62]:
class HuberLoss(tf.keras.losses.Loss):
    def __init__(self,threshold=1.0,**kwargs):
        self.threshold=threshold
        super().__init__(**kwargs)
        
    def call(self,y_true,y_pred):
        error= y_true - y_pred
        is_small_error= tf.abs(error) < self.threshold
        square_loss= tf.square(error) /2
        linear_loss= self.threshold * tf.abs(error) - self.threshold**2 / 2
        return tf.where(is_small_error,square_loss,linear_loss)

    def get_config(self):
        base_config=super().get_config()
        return {**base_config,"threshold":self.threshold}

In [63]:
tf.keras.utils.set_random_seed(42)

model=tf.keras.Sequential([
    tf.keras.layers.InputLayer(shape=input_shape),
    tf.keras.layers.Dense(30,activation="relu",
                         kernel_initializer="he_normal"),
    tf.keras.layers.Dense(1)
])


In [64]:
model.compile(loss=HuberLoss(1.4),optimizer="nadam",metrics=["mae"])

In [65]:
model.fit(X_train_scaled,y_train,
         epochs=3,
         validation_data=(X_valid_scaled,y_valid))

Epoch 1/3
363/363 ━━━━━━━━━━━━━━━━━━━━ 1s 683us/step - loss: 0.9035 - mae: 1.1389 - val_loss: 0.4178 - val_mae: 0.6595
Epoch 2/3
363/363 ━━━━━━━━━━━━━━━━━━━━ 0s 522us/step - loss: 0.2919 - mae: 0.5737 - val_loss: 0.2988 - val_mae: 0.5456
Epoch 3/3
363/363 ━━━━━━━━━━━━━━━━━━━━ 0s 523us/step - loss: 0.2429 - mae: 0.5161 - val_loss: 0.2395 - val_mae: 0.4911


In [66]:
model.save("my_custom_loss_threshold_class_model.keras")

In [67]:
model=tf.keras.models.load_model("my_custom_loss_threshold_class_model.keras",
                                custom_objects={"HuberLoss":HuberLoss})

In [68]:
model.fit(X_train_scaled,y_train,
         epochs=3,
          validation_data=(X_valid_scaled,y_valid)
         )

Epoch 1/3
363/363 ━━━━━━━━━━━━━━━━━━━━ 0s 670us/step - loss: 0.2189 - mae: 0.4864 - val_loss: 0.2084 - val_mae: 0.4635
Epoch 2/3
363/363 ━━━━━━━━━━━━━━━━━━━━ 0s 526us/step - loss: 0.2063 - mae: 0.4703 - val_loss: 0.1820 - val_mae: 0.4415
Epoch 3/3
363/363 ━━━━━━━━━━━━━━━━━━━━ 0s 520us/step - loss: 0.1988 - mae: 0.4611 - val_loss: 0.1821 - val_mae: 0.4395


In [69]:
model.loss.threshold

1.4

## Other Custom Functions

In [71]:
def my_softplus(z):
    return tf.math.log(1+tf.exp(z))

def my_glorot_initializer(shape,dtype=tf.float32):
    stddev= tf.sqrt(2 / (shape[0] + shape[1]))
    
    return tf.random.normal(shape,stddev=stddev,dtype=dtype)

def my_l1_regu(weights):
    return 0.01 * tf.reduce_sum(tf.abs(weights))

def my_positive_weights(weights):
    return tf.where(weights<0. ,tf.zeros_like(weights),weights)

In [72]:
class MyL1Regularizer(tf.keras.regularizers.Regularizer):
    def __init__(self, factor):
        self.factor = factor

    def __call__(self, weights):
        return self.factor * tf.reduce_sum(tf.abs(weights))

    def get_config(self):
        return {"factor": self.factor}


In [73]:
class MyPositiveWeights(tf.keras.constraints.Constraint):
    def __init__(self):
        pass
    def __call__(self,weights):
        return tf.where(weights<0. ,tf.zeros_like(weights),weights)
    def get_config(self):
        return {}
    

In [74]:
tf.keras.utils.set_random_seed(42)

model=tf.keras.Sequential([
    tf.keras.layers.InputLayer(shape=input_shape),
    tf.keras.layers.Dense(30,activation=my_softplus,
                          kernel_initializer=my_glorot_initializer,
                          kernel_regularizer=MyL1Regularizer(factor=0.01),
                          kernel_constraint=MyPositiveWeights()
                           ),
                         
    tf.keras.layers.Dense(1)
])
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_4 (Dense)                 │ (None, 30)             │           270 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 1)              │            31 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 301 (1.18 KB)

 Trainable params: 301 (1.18 KB)

 Non-trainable params: 0 (0.00 B)

In [75]:
model.compile(loss=HuberLoss(1.2),optimizer="nadam",metrics=["mae"])

In [76]:
history=model.fit(X_train_scaled,y_train,
                 epochs=4,
                 validation_data=(X_valid_scaled,y_valid))

Epoch 1/4
363/363 ━━━━━━━━━━━━━━━━━━━━ 1s 705us/step - loss: 1.1080 - mae: 1.2316 - val_loss: inf - val_mae: inf
Epoch 2/4
363/363 ━━━━━━━━━━━━━━━━━━━━ 0s 539us/step - loss: 0.4222 - mae: 0.6201 - val_loss: inf - val_mae: inf
Epoch 3/4
363/363 ━━━━━━━━━━━━━━━━━━━━ 0s 543us/step - loss: 0.3799 - mae: 0.6103 - val_loss: inf - val_mae: inf
Epoch 4/4
363/363 ━━━━━━━━━━━━━━━━━━━━ 0s 536us/step - loss: 0.3623 - mae: 0.6105 - val_loss: 0.3385 - val_mae: 0.5923


## Custom Metrics

In [78]:
tf.keras.utils.set_random_seed(42)
model=tf.keras.Sequential([
    tf.keras.layers.InputLayer(shape=input_shape),
    tf.keras.layers.Dense(30,activation="relu",
                         kernel_initializer="he_normal"),
    tf.keras.layers.Dense(1)
])

In [79]:
model.compile(loss="mse",optimizer="nadam",metrics=[HuberLoss(2)])

In [80]:
model.fit(X_train_scaled,y_train,
         epochs=3,
         validation_data=(X_valid_scaled,y_valid))

Epoch 1/3
363/363 ━━━━━━━━━━━━━━━━━━━━ 1s 682us/step - huber_loss_2: 1.0788 - loss: 2.5942 - val_huber_loss_2: 0.5646 - val_loss: 21.3898
Epoch 2/3
363/363 ━━━━━━━━━━━━━━━━━━━━ 0s 519us/step - huber_loss_2: 0.3403 - loss: 0.7644 - val_huber_loss_2: 0.4281 - val_loss: 11.2129
Epoch 3/3
363/363 ━━━━━━━━━━━━━━━━━━━━ 0s 549us/step - huber_loss_2: 0.2803 - loss: 0.6047 - val_huber_loss_2: 0.3411 - val_loss: 5.6292


In [81]:
tf.keras.utils.set_random_seed(42)
model=tf.keras.Sequential([
    tf.keras.layers.InputLayer(shape=input_shape),
    tf.keras.layers.Dense(30,activation="relu",
                         kernel_initializer="he_normal"),
    tf.keras.layers.Dense(1)
])

In [82]:
model.compile(loss="mse",optimizer="nadam",metrics=[create_huber(2)])

In [83]:
model.fit(X_train_scaled,y_train,
         epochs=3,
         validation_data=(X_valid_scaled,y_valid))

Epoch 1/3
363/363 ━━━━━━━━━━━━━━━━━━━━ 1s 677us/step - huber_fn: 1.0788 - loss: 2.5942 - val_huber_fn: 0.5648 - val_loss: 21.3898
Epoch 2/3
363/363 ━━━━━━━━━━━━━━━━━━━━ 0s 517us/step - huber_fn: 0.3403 - loss: 0.7644 - val_huber_fn: 0.4283 - val_loss: 11.2129
Epoch 3/3
363/363 ━━━━━━━━━━━━━━━━━━━━ 0s 530us/step - huber_fn: 0.2803 - loss: 0.6047 - val_huber_fn: 0.3412 - val_loss: 5.6292


In [84]:
model.compile(loss=create_huber(2),optimizer="nadam",metrics=[create_huber(2)])

In [85]:
model.fit(X_train_scaled,y_train,
         epochs=3,
         validation_data=(X_valid_scaled,y_valid))


Epoch 1/3
363/363 ━━━━━━━━━━━━━━━━━━━━ 1s 684us/step - huber_fn: 0.2443 - loss: 0.2443 - val_huber_fn: 0.2984 - val_loss: 0.2984
Epoch 2/3
363/363 ━━━━━━━━━━━━━━━━━━━━ 0s 520us/step - huber_fn: 0.2206 - loss: 0.2206 - val_huber_fn: 0.2439 - val_loss: 0.2439
Epoch 3/3
363/363 ━━━━━━━━━━━━━━━━━━━━ 0s 519us/step - huber_fn: 0.2101 - loss: 0.2101 - val_huber_fn: 0.2090 - val_loss: 0.2090


### Streaming Metrics

In [87]:
precision=tf.keras.metrics.Precision()

In [88]:
precision([0, 1, 1, 1, 0, 1, 0, 1], [1, 1, 0, 1, 0, 1, 0, 1]) # precision = 4 / 5 = 0.8

<tf.Tensor: shape=(), dtype=float32, numpy=0.800000011920929>

In [89]:
precision([0, 1, 0, 0, 1, 0, 1, 1], [1, 0, 1, 1, 0, 0, 0, 0]) #precision=0/3=0 

<tf.Tensor: shape=(), dtype=float32, numpy=0.5>

In [90]:
precision.result()   #Final result-> 4/(5+3)=0.5

<tf.Tensor: shape=(), dtype=float32, numpy=0.5>

In [91]:
precision.variables

[<Variable path=precision/true_positives, shape=(1,), dtype=float32, value=[4.]>,
 <Variable path=precision/false_positives, shape=(1,), dtype=float32, value=[4.]>]

In [92]:
precision.reset_state()

In [93]:
precision.result()

<tf.Tensor: shape=(), dtype=float32, numpy=0.0>

In [94]:
class HuberMetric(tf.keras.metrics.Metric):
    def __init__(self,threshold=1.0,**kwargs):
        super().__init__(**kwargs)
        self.threshold=threshold
        self.huber_fn=create_huber(threshold)
        self.total=self.add_weight(name="total",initializer="zeros") #Ek TensorFlow variable banao jiska naam total ho aur shuru mein value 0.0 ho.
        self.count=self.add_weight(name="count",initializer="zeros")

    def update_state(self,y_true,y_pred,sample_weight=None):
        sample_metrics=self.huber_fn(y_true,y_pred)
        self.total.assign_add(tf.reduce_sum(sample_metrics))
        self.count.assign_add(tf.cast(tf.size(y_true),tf.float32))

    def result(self):
        return self.total/self.count

    def get_config(self):
        base_config=super().get_config()
        return {**base_config,"threshold":self.threshold}

In [95]:
m=HuberMetric(3.0)

m(tf.constant([[3.]]),tf.constant([[12.]]))

#error->12-3=9
#9>3 so linear loss
# total-> 3*9 - 3^2 /2 =22.5
# count=1
#result=22.5/1

<tf.Tensor: shape=(), dtype=float32, numpy=22.5>

In [96]:
m(tf.constant([[2.],[3.]]),tf.constant([[1.],[7.]]))

# total -> total + (|1-2|²)/2 + 3*|7-3|-3²/2= 22.5+8=30.5
#Count -> count + 2 =1+2=3
#result= 30.5/3=10.1666

<tf.Tensor: shape=(), dtype=float32, numpy=10.166666984558105>

In [97]:
m.result()

<tf.Tensor: shape=(), dtype=float32, numpy=10.166666984558105>

In [98]:
m.variables

[<Variable path=huber_metric/total, shape=(), dtype=float32, value=30.5>,
 <Variable path=huber_metric/count, shape=(), dtype=float32, value=3.0>]

In [99]:
m.reset_state()

In [100]:
m.variables

[<Variable path=huber_metric/total, shape=(), dtype=float32, value=0.0>,
 <Variable path=huber_metric/count, shape=(), dtype=float32, value=0.0>]

In [101]:
tf.keras.utils.set_random_seed(42)

model=tf.keras.Sequential([
    tf.keras.layers.InputLayer(shape=input_shape),
    tf.keras.layers.Dense(30,activation="relu",
                         kernel_initializer="he_normal"),
    tf.keras.layers.Dense(1)
])

In [102]:
model.compile(loss=HuberLoss(2),
             optimizer="nadam",
             metrics=[HuberMetric(2)])

In [103]:
model.fit(X_train_scaled,y_train,
         epochs=4,
         validation_data=(X_valid_scaled,y_valid))

Epoch 1/4
363/363 ━━━━━━━━━━━━━━━━━━━━ 1s 675us/step - huber_metric_1: 1.0512 - loss: 1.0512 - val_huber_metric_1: 0.5086 - val_loss: 0.5086
Epoch 2/4
363/363 ━━━━━━━━━━━━━━━━━━━━ 0s 518us/step - huber_metric_1: 0.3170 - loss: 0.3170 - val_huber_metric_1: 0.3527 - val_loss: 0.3527
Epoch 3/4
363/363 ━━━━━━━━━━━━━━━━━━━━ 0s 520us/step - huber_metric_1: 0.2612 - loss: 0.2612 - val_huber_metric_1: 0.2689 - val_loss: 0.2689
Epoch 4/4
363/363 ━━━━━━━━━━━━━━━━━━━━ 0s 516us/step - huber_metric_1: 0.2328 - loss: 0.2328 - val_huber_metric_1: 0.2207 - val_loss: 0.2207


In [104]:
model.save("my_custom_huber_metric_model.keras")

In [105]:
model=tf.keras.models.load_model("my_custom_huber_metric_model.keras",
                                custom_objects={"HuberLoss":HuberLoss,
                                               "HuberMetric":HuberMetric})

In [106]:
model.fit(X_train_scaled,y_train,
         epochs=3,
         validation_data=(X_valid_scaled,y_valid))

Epoch 1/3
363/363 ━━━━━━━━━━━━━━━━━━━━ 0s 665us/step - huber_metric_1: 0.2178 - loss: 0.2178 - val_huber_metric_1: 0.1899 - val_loss: 0.1899
Epoch 2/3
363/363 ━━━━━━━━━━━━━━━━━━━━ 0s 511us/step - huber_metric_1: 0.2093 - loss: 0.2093 - val_huber_metric_1: 0.1996 - val_loss: 0.1996
Epoch 3/3
363/363 ━━━━━━━━━━━━━━━━━━━━ 0s 513us/step - huber_metric_1: 0.2036 - loss: 0.2036 - val_huber_metric_1: 0.2243 - val_loss: 0.2243


In [107]:
class HuberMetric(tf.keras.metrics.Mean):
    def __init__(self,threshold=1.0,name="HuberMetric",dtype=None):
        self.threshold=threshold
        self.huber_fn=create_huber(threshold)
        super().__init__(name=name,dtype=dtype)

    def update_state(self,y_true,y_pred,sample_weight=None):
        metric=self.huber_fn(y_true,y_pred)
        super(HuberMetric,self).update_state(metric,sample_weight)

    def get_config(self):
        base_config=super().get_config()
        return {**base_config,"threshold":self.threshold}

In [108]:
tf.keras.utils.set_random_seed(42)

model=tf.keras.Sequential([
    tf.keras.layers.InputLayer(shape=input_shape),
    tf.keras.layers.Dense(30,activation="relu",
                         kernel_initializer="he_normal"),
    tf.keras.layers.Dense(1)
])

In [109]:
model.compile(loss=HuberLoss(2),
             optimizer="nadam",
                 weighted_metrics=[HuberMetric(2)])

In [110]:
np.random.seed(42)
sample_weights=np.random.rand(len(y_train))
model.fit(X_train_scaled,y_train,
         epochs=4,
         sample_weight=sample_weights,
         validation_data=(X_valid_scaled,y_valid))

Epoch 1/4
363/363 ━━━━━━━━━━━━━━━━━━━━ 1s 687us/step - HuberMetric: 1.0599 - loss: 0.5274 - val_HuberMetric: 0.5222 - val_loss: 0.5222
Epoch 2/4
363/363 ━━━━━━━━━━━━━━━━━━━━ 0s 530us/step - HuberMetric: 0.3215 - loss: 0.1598 - val_HuberMetric: 0.3468 - val_loss: 0.3468
Epoch 3/4
363/363 ━━━━━━━━━━━━━━━━━━━━ 0s 523us/step - HuberMetric: 0.2647 - loss: 0.1316 - val_HuberMetric: 0.2743 - val_loss: 0.2743
Epoch 4/4
363/363 ━━━━━━━━━━━━━━━━━━━━ 0s 519us/step - HuberMetric: 0.2371 - loss: 0.1178 - val_HuberMetric: 0.2428 - val_loss: 0.2428


In [111]:
model.save("my_custom_huber_metric_model_v2.keras")

In [112]:
model=tf.keras.models.load_model("my_custom_huber_metric_model.keras",
                                custom_objects={"HuberLoss":HuberLoss,
                                               "HuberMetric":HuberMetric})

In [113]:
model.fit(X_train_scaled,y_train,
         epochs=2)

Epoch 1/2
363/363 ━━━━━━━━━━━━━━━━━━━━ 0s 393us/step - huber_metric_1: 0.2178 - loss: 0.2178 
Epoch 2/2
363/363 ━━━━━━━━━━━━━━━━━━━━ 0s 379us/step - huber_metric_1: 0.2093 - loss: 0.2093


## Custom Layers

In [115]:
exp_layer=tf.keras.layers.Lambda(lambda x:tf.exp(x))

In [116]:
exp_layer(tf.constant([-2.,3.,5.]))

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1.3533528e-01, 2.0085537e+01, 1.4841316e+02], dtype=float32)>

In [117]:
tf.keras.utils.set_random_seed(42)

model=tf.keras.Sequential([
    tf.keras.layers.InputLayer(shape=input_shape),
    tf.keras.layers.Dense(30,activation="relu"),
    tf.keras.layers.Dense(1),
    exp_layer
])

In [118]:
model.compile(loss="mse",optimizer="sgd",metrics=[HuberLoss(2.0)])

In [119]:
model.fit(X_train_scaled,y_train,
         epochs=2)

Epoch 1/2
363/363 ━━━━━━━━━━━━━━━━━━━━ 0s 354us/step - huber_loss_5: 0.5644 - loss: 1.2350 
Epoch 2/2
363/363 ━━━━━━━━━━━━━━━━━━━━ 0s 340us/step - huber_loss_5: 0.2871 - loss: 0.6130


In [120]:
class MyDense(tf.keras.layers.Layer):
    def __init__(self,units,activation=None,**kwargs):
        super().__init__(**kwargs)
        self.units=units
        self.activation=tf.keras.activations.get(activation)

    def build(self,batch_input_size):
        self.kernel=self.add_weight(
            name="kernel",
            initializer="he_normal",
            shape=[batch_input_size[-1],self.units]
        )
        self.bias=self.add_weight(
            name="bias",
            shape=[self.units],
            initializer="zeros"
        )
        
    def call(self,X):
        return self.activation(X@self.kernel + self.bias)

    def get_config(self):
        base_config=super().get_config()
        return {**base_config,"units":self.units,
               "activation":tf.keras.activations.serialize(self.activation)} #Converts function to string name for saving


In [121]:
tf.keras.utils.set_random_seed(42)
model = tf.keras.Sequential([
    tf.keras.layers.InputLayer(shape=input_shape),
    MyDense(30, activation="relu"),
    MyDense(1)
])
model.compile(loss="mse", optimizer="nadam")
model.fit(X_train_scaled, y_train, epochs=2,
          validation_data=(X_valid_scaled, y_valid))

Epoch 1/2
363/363 ━━━━━━━━━━━━━━━━━━━━ 0s 608us/step - loss: 5.7265 - val_loss: 6.9255
Epoch 2/2
363/363 ━━━━━━━━━━━━━━━━━━━━ 0s 487us/step - loss: 0.9550 - val_loss: 2.6011


In [122]:
model.evaluate(X_test_scaled,y_test)

162/162 ━━━━━━━━━━━━━━━━━━━━ 0s 312us/step - loss: 0.7227


0.7036542296409607

In [123]:
model.save("my_custom_layer_model.keras")

In [124]:
model=tf.keras.models.load_model("my_custom_layer_model.keras",
                                custom_objects={"MyDense":MyDense})

In [125]:
model.fit(X_train_scaled,y_train,
         epochs=2)

Epoch 1/2
363/363 ━━━━━━━━━━━━━━━━━━━━ 0s 373us/step - loss: 0.7034 
Epoch 2/2
363/363 ━━━━━━━━━━━━━━━━━━━━ 0s 360us/step - loss: 0.5803


In [126]:
class MyMultilayer(tf.keras.layers.Layer):
    def call(self,inputs):
        input1,input2=inputs
        added=input1+input2
        multiplied=input1*input2
        divided=input1/input2

        return [added,multiplied,divided]

In [127]:
input1=tf.keras.layers.Input(shape=[3])
input2=tf.keras.layers.Input(shape=[3])

MyMultilayer()((input1,input2))

[<KerasTensor shape=(None, 3), dtype=float32, sparse=False, ragged=False, name=keras_tensor_50>,
 <KerasTensor shape=(None, 3), dtype=float32, sparse=False, ragged=False, name=keras_tensor_51>,
 <KerasTensor shape=(None, 3), dtype=float32, sparse=False, ragged=False, name=keras_tensor_52>]

In [128]:
class MyGaussianNoise(tf.keras.layers.Layer):
    def __init__(self,stddev,**kwargs):
        super().__init__(**kwargs)
        self.stddev=stddev

    def call(self,X,training=None):
        if training:
            noise=tf.random.normal(tf.shape(X),stddev=self.stddev)
            return X+noise
        else:
            return X
        

In [129]:
tf.keras.utils.set_random_seed(42)

model=tf.keras.Sequential([
    tf.keras.layers.InputLayer(shape=input_shape),
    MyGaussianNoise(stddev=1.0),
    tf.keras.layers.Dense(20,activation="relu",
                         kernel_initializer="he_normal"),
    tf.keras.layers.Dense(1)
])
model.compile(loss="mse",optimizer="nadam",metrics=[HuberMetric(1)])
model.fit(X_train_scaled,y_train,
         epochs=3,
         validation_data=(X_valid_scaled,y_valid))
model.evaluate(X_test_scaled,y_test)

Epoch 1/3
363/363 ━━━━━━━━━━━━━━━━━━━━ 1s 672us/step - HuberMetric: 1.2976 - loss: 5.0938 - val_HuberMetric: 0.5893 - val_loss: 8.4476
Epoch 2/3
363/363 ━━━━━━━━━━━━━━━━━━━━ 0s 520us/step - HuberMetric: 0.5946 - loss: 1.6268 - val_HuberMetric: 0.4574 - val_loss: 3.1225
Epoch 3/3
363/363 ━━━━━━━━━━━━━━━━━━━━ 0s 519us/step - HuberMetric: 0.4911 - loss: 1.2658 - val_HuberMetric: 0.3873 - val_loss: 1.5090
162/162 ━━━━━━━━━━━━━━━━━━━━ 0s 332us/step - HuberMetric: 0.3772 - loss: 0.9654


[0.9787654280662537, 0.37903374433517456]

## Custom Models

In [131]:
class ResidualBlock(tf.keras.layers.Layer):
    def __init__(self,n_layers,n_neurons,**kwargs):
        super().__init__(**kwargs)
        self.hidded=[tf.keras.layers.Dense(n_neurons,activation="relu",
                                          kernel_initializer="he_normal")
                    for _ in range(n_layers)]

    def call(self,inputs):
        Z=inputs
        for layer in self.hidded:
            Z=layer(Z)
        return inputs+Z

In [132]:
class ResidualRegressor(tf.keras.Model):
    def __init__(self,output_dim,**kwargs):
        super().__init__(**kwargs)
        self.output_dim=output_dim
        self.hidden1=tf.keras.layers.Dense(30,activation="relu",
                                          kernel_initializer="he_normal")
        self.block1=ResidualBlock(2,30)
        self.block2=ResidualBlock(2,30)
        self.out=tf.keras.layers.Dense(output_dim)

    def call(self,inputs):
        Z=self.hidden1(inputs)
        for _ in range(1+3):
            Z=self.block1(Z)
        Z=self.block2(Z)
        return self.out(Z)

    def get_config(self):
        base_config=super().get_config()
        return {**base_config,"output_dim":self.output_dim}
    

In [133]:
tf.keras.utils.set_random_seed(42)

model=ResidualRegressor(1)
model.compile(loss="mse",optimizer="nadam",metrics=[HuberMetric(1)])
history=model.fit(X_train_scaled,y_train,
                 epochs=3)
model.evaluate(X_test_scaled,y_test)

Epoch 1/3
363/363 ━━━━━━━━━━━━━━━━━━━━ 1s 539us/step - HuberMetric: 4.6533 - loss: 123.5810    
Epoch 2/3
363/363 ━━━━━━━━━━━━━━━━━━━━ 0s 530us/step - HuberMetric: 0.5357 - loss: 1.5416
Epoch 3/3
363/363 ━━━━━━━━━━━━━━━━━━━━ 0s 529us/step - HuberMetric: 0.4112 - loss: 1.0556
162/162 ━━━━━━━━━━━━━━━━━━━━ 0s 392us/step - HuberMetric: 0.3495 - loss: 0.8952


[0.9233353734016418, 0.3550209105014801]

In [134]:
model.save("my_custom_model.keras")

In [135]:
model=tf.keras.models.load_model("my_custom_model.keras",
                                custom_objects={"ResidualRegressor":ResidualRegressor,
                                               "HuberMetric":HuberMetric})

In [136]:
model.fit(X_train_scaled,y_train,epochs=2)
model.evaluate(X_test_scaled,y_test)

Epoch 1/2
363/363 ━━━━━━━━━━━━━━━━━━━━ 1s 557us/step - HuberMetric: 0.3643 - loss: 0.9670  
Epoch 2/2
363/363 ━━━━━━━━━━━━━━━━━━━━ 0s 549us/step - HuberMetric: 0.3556 - loss: 0.9675
162/162 ━━━━━━━━━━━━━━━━━━━━ 0s 395us/step - HuberMetric: 0.3411 - loss: 0.9094


[1.007361888885498, 0.3495626747608185]

In [137]:
tf.keras.utils.set_random_seed(42)

block1=ResidualBlock(2,30)
model=tf.keras.Sequential([
    tf.keras.layers.Dense(30,activation="relu",
                         kernel_initializer="he_normal"),
    block1,
    block1,
    block1,
    block1,
    ResidualBlock(2,30),
    tf.keras.layers.Dense(1)
])

In [138]:
model.compile(loss="mse",optimizer="nadam")
model.fit(X_train_scaled,y_train,epochs=2)

Epoch 1/2
363/363 ━━━━━━━━━━━━━━━━━━━━ 1s 522us/step - loss: 19.1188   
Epoch 2/2
363/363 ━━━━━━━━━━━━━━━━━━━━ 0s 512us/step - loss: 0.9171


In [139]:
model=tf.keras.Sequential([
    tf.keras.layers.Dense(20,activation="relu",kernel_initializer="he_normal"),
    ResidualBlock(2,30),
    ResidualRegressor(1)
])

## Losses Based on Models Internals

In [141]:
class ReconstructingRegressor(tf.keras.Model):
    def __init__(self,out_dim,**kwargs):
        super().__init__(**kwargs)
        self.hidden=[tf.keras.layers.Dense(30,activation="relu",kernel_initializer="he_normal")
                    for _ in range(5)]
        self.out=tf.keras.layers.Dense(out_dim)

    def build(self,batch_input_size):
        n_inputs=batch_input_size[-1]
        self.reconstruct=tf.keras.layers.Dense(n_inputs)

    def call(self,inputs,training=None):

        Z=inputs
        for layer in self.hidden:
            Z=layer(Z)

        reconstruction=self.reconstruct(Z)
        reconstruction_loss=tf.reduce_mean(tf.square(reconstruction-inputs))
        self.add_loss(0.05*reconstruction_loss)
        return self.out(Z)

In [142]:
tf.keras.utils.set_random_seed(42)

model=ReconstructingRegressor(1)
model.compile(loss="mse",optimizer="nadam")
model.fit(X_train_scaled,y_train,
         epochs=3)

Epoch 1/3
363/363 ━━━━━━━━━━━━━━━━━━━━ 1s 504us/step - loss: 1.1051  
Epoch 2/3
363/363 ━━━━━━━━━━━━━━━━━━━━ 0s 498us/step - loss: 0.5082
Epoch 3/3
363/363 ━━━━━━━━━━━━━━━━━━━━ 0s 711us/step - loss: 0.4392


## Computing Gradients Using Auto-Diff

In [144]:
def f(x,y):
    return x*x*y+y+2.0

def derivative(f,x,y,x_eps,y_eps):
    return (f(x+x_eps,y+y_eps)-f(x,y))/(x_eps+y_eps)

df_dx=derivative(f,3,4,0.00001,0)
df_dy=derivative(f,3,4,0,0.00001)

In [145]:
df_dx

24.000039999805264

In [146]:
df_dy

10.000000000331966

In [147]:
w1,w2=tf.Variable(3.),tf.Variable(4.)
with tf.GradientTape() as tape:
    z=f(w1,w2)
gradients = tape.gradient(z, [w1, w2])

In [148]:
gradients

[<tf.Tensor: shape=(), dtype=float32, numpy=24.0>,
 <tf.Tensor: shape=(), dtype=float32, numpy=10.0>]

In [149]:
with tf.GradientTape() as tape:
    z=f(w1,w2)
dz_dw1=tape.gradient(z,w1)
try:
    dz_dw2=tape.gradient(z,w2)
except RuntimeError as ex:
    print(ex)

A non-persistent GradientTape can only be used to compute one set of gradients (or jacobians)


In [150]:
with tf.GradientTape(persistent=True) as tape:   
    z=f(w1,w2)
dz_dw1=tape.gradient(z,w1)
dz_dw2=tape.gradient(z,w2)
del tape


In [151]:
dz_dw1, dz_dw2

(<tf.Tensor: shape=(), dtype=float32, numpy=24.0>,
 <tf.Tensor: shape=(), dtype=float32, numpy=10.0>)

In [152]:
c1,c2=tf.constant(3.),tf.constant(4.)
with tf.GradientTape() as tape:
    z=f(c1,c2)
gradients=tape.gradient(z,[c1,c2])

In [153]:
gradients

[None, None]

In [154]:
c1,c2=tf.constant(3.),tf.constant(4.)
with tf.GradientTape() as tape:
    tape.watch([c1,c2])
    z=f(c1,c2)
gradients=tape.gradient(z,[c1,c2])

In [155]:
gradients

[<tf.Tensor: shape=(), dtype=float32, numpy=24.0>,
 <tf.Tensor: shape=(), dtype=float32, numpy=10.0>]

In [156]:
with tf.GradientTape() as tape:
    z1=f(w1,w2+2.)
    z2=f(w1,w2+3.)
    z3=f(w1,w2+4.)
tape.gradient([z1,z2,z3],[w1,w2])

[<tf.Tensor: shape=(), dtype=float32, numpy=126.0>,
 <tf.Tensor: shape=(), dtype=float32, numpy=30.0>]

In [157]:
with tf.GradientTape() as tape:
    z1=f(w1,w2+2.)
    z2=f(w1,w2+3.)
    z3=f(w1,w2+4.)
    z=z1,z2,z3
tape.gradient(z,[w1,w2])
    

[<tf.Tensor: shape=(), dtype=float32, numpy=126.0>,
 <tf.Tensor: shape=(), dtype=float32, numpy=30.0>]

In [158]:
with tf.GradientTape() as tape:
    z1=f(w1,w2+2.)
    z2=f(w1,w2+3.)
    z3=f(w1,w2+4.)
    output=tf.stack([z1,z2,z3])
tape.gradient(output,[w1,w2])

[<tf.Tensor: shape=(), dtype=float32, numpy=126.0>,
 <tf.Tensor: shape=(), dtype=float32, numpy=30.0>]

In [159]:
with tf.GradientTape(persistent=True) as hessian_tape:        # second order derivative
    with tf.GradientTape() as jacobian_tape:                 #first order derivative
        z=f(w1,w2)
    jacobians=jacobian_tape.gradient(z,[w1,w2])
hessians=[hessian_tape.gradient(jacobian,[w1,w2])
                              for jacobian in jacobians]

del hessian_tape

In [160]:
jacobians

[<tf.Tensor: shape=(), dtype=float32, numpy=24.0>,
 <tf.Tensor: shape=(), dtype=float32, numpy=10.0>]

In [161]:
hessians

[[<tf.Tensor: shape=(), dtype=float32, numpy=8.0>,
  <tf.Tensor: shape=(), dtype=float32, numpy=6.0>],
 [<tf.Tensor: shape=(), dtype=float32, numpy=6.0>, None]]

In [162]:
def f(w1,w2):
    return w1*w1*w2 + tf.stop_gradient(w2+2.0)

with tf.GradientTape() as tape:
    z=f(w1,w2)
gradients=tape.gradient(z,[w1,w2])

In [163]:
gradients

[<tf.Tensor: shape=(), dtype=float32, numpy=24.0>,
 <tf.Tensor: shape=(), dtype=float32, numpy=9.0>]

## Custom Training Loops

In [165]:
tf.keras.utils.set_random_seed(42)
l2_reg=tf.keras.regularizers.l2(0.05)
model=tf.keras.Sequential([
    tf.keras.layers.Dense(30,activation="relu",
                         kernel_initializer="he_normal",
                         kernel_regularizer=l2_reg),
    tf.keras.layers.Dense(1,kernel_regularizer=l2_reg)
])

In [166]:
def random_batch(X,y,batch_size=32):
    idx=np.random.randint(len(X),size=batch_size)
    return X[idx],y[idx]

In [167]:
tf.keras.utils.set_random_seed(42)

n_epoch=5
batch_size=32
n_steps=len(X_train)//batch_size
optimizer=tf.keras.optimizers.SGD(learning_rate=0.01)
loss_fn=tf.keras.losses.MeanSquaredError()
mean_loss=tf.keras.metrics.Mean()
metrics=[tf.keras.metrics.MeanAbsoluteError()]

In [168]:
def print_status_bar(step,total,loss,metrics=None):
    metrics=" - ".join([f"{m.name} : {m.result():.4f}"
                      for m in [loss]+(metrics or [])])
    end="" if step<total else "\n"
    print(f"\r{step}/{total}-"+metrics,end=end)

In [169]:
for epoch in range(1,n_epoch+1):
    print(f"Epoch:{epoch}/{n_epoch}")
    for step in range(1,n_steps+1):
        X_batch,y_batch=random_batch(X_train_scaled,y_train)

        # Forward pass and loss compute
        with tf.GradientTape() as tape:                   
            y_pred=model(X_batch,training=True)
            main_loss=tf.reduce_mean(loss_fn(y_batch,y_pred))   
            loss=tf.add_n([main_loss]+model.losses)
            
        #Backpropagation
        gradients=tape.gradient(loss,model.trainable_variables)
        clipped_gradients=[tf.clip_by_norm(g,1) for g in gradients] #Custom Clipping (manual)
        optimizer.apply_gradients(zip(clipped_gradients,model.trainable_variables))

        #Apply constraint if any
        for variable in model.variables:
            if variable.constraint is not None:
                variable.assign(variable.constraint(variable))

        mean_loss(loss)

        for metric in metrics:
            metric(y_batch,y_pred)

        print_status_bar(step,n_steps,mean_loss,metrics)

    for metric in [mean_loss]+metrics:
        metric.reset_state()


Epoch:1/5
362/362-mean : 4.1141 - mean_absolute_error : 0.7109
Epoch:2/5
362/362-mean : 2.0594 - mean_absolute_error : 0.5270
Epoch:3/5
362/362-mean : 1.2815 - mean_absolute_error : 0.4978
Epoch:4/5
362/362-mean : 0.9340 - mean_absolute_error : 0.4935
Epoch:5/5
362/362-mean : 0.7752 - mean_absolute_error : 0.4996


# TensorFlow Functions and Graphs

In [171]:
def cube(x):
    return x**3

In [172]:
cube(2)

8

In [173]:
cube(tf.constant(2.))      # Eager execution

<tf.Tensor: shape=(), dtype=float32, numpy=8.0>

In [174]:
tf_cube=tf.function(cube)   # Graph execution

In [175]:
tf_cube

In [176]:
tf_cube(2)

<tf.Tensor: shape=(), dtype=int32, numpy=8>

In [177]:
tf_cube(tf.constant(2))
tf_cube(tf.constant(4))

<tf.Tensor: shape=(), dtype=int32, numpy=64>

In [178]:
@tf.function
def tf_cube(x):
    return x ** 3


In [179]:
tf_cube(tf.constant(2))  

<tf.Tensor: shape=(), dtype=int32, numpy=8>

In [180]:
tf_cube.python_function(2)

8

In [181]:
import tensorflow as tf

@tf.function(input_signature=[tf.TensorSpec(shape=(), dtype=tf.float32)])
def square(x):
    print("Tracing:", x)
    return x ** 2

a = tf.constant(3.0, dtype=tf.float32)
b = tf.constant(4.0, dtype=tf.float32)
c = tf.constant(5.0, dtype=tf.float32)

print(square(a))
print(square(b)) 
print(square(c))  


Tracing: Tensor("x:0", shape=(), dtype=float32)
tf.Tensor(9.0, shape=(), dtype=float32)
tf.Tensor(16.0, shape=(), dtype=float32)
tf.Tensor(25.0, shape=(), dtype=float32)


### TF Functions and Concrete Functions

In [183]:
concrete_fn=tf_cube.get_concrete_function(tf.constant(2.0))

In [184]:
concrete_fn(tf.constant(3.0))

<tf.Tensor: shape=(), dtype=float32, numpy=27.0>

In [185]:
concrete_fn is tf_cube.get_concrete_function(tf.constant(4.0))

True

In [186]:
concrete_fn is tf_cube.get_concrete_function(tf.constant(4))

False

###  Exploring Function Defination and Graphs

In [188]:
concrete_fn.graph

In [189]:
ops=concrete_fn.graph.get_operations()
ops

[<tf.Operation 'x' type=Placeholder>,
 <tf.Operation 'pow/y' type=Const>,
 <tf.Operation 'pow' type=Pow>,
 <tf.Operation 'Identity' type=Identity>]

In [190]:
pow_op=ops[2]
list(pow_op.inputs)

[<tf.Tensor 'x:0' shape=() dtype=float32>,
 <tf.Tensor 'pow/y:0' shape=() dtype=float32>]

In [191]:
pow_op.outputs

[<tf.Tensor 'pow:0' shape=() dtype=float32>]

In [192]:
concrete_fn.graph.get_operation_by_name('x')

<tf.Operation 'x' type=Placeholder>

In [193]:
concrete_fn.graph.get_tensor_by_name('Identity:0')

<tf.Tensor 'Identity:0' shape=() dtype=float32>

In [194]:
concrete_fn.function_def.signature

name: "__inference_tf_cube_570321"
input_arg {
  name: "x"
  type: DT_FLOAT
}
output_arg {
  name: "identity"
  type: DT_FLOAT
}

### How TF Functions Trace Python Functions to Extract Their Computational Graph

In [196]:
@tf.function

def tf_cube(x):
    print(f"x={x}")
    return x**2


In [197]:
result=tf_cube(tf.constant(2.0))

x=Tensor("x:0", shape=(), dtype=float32)


In [198]:
result

<tf.Tensor: shape=(), dtype=float32, numpy=4.0>

In [199]:
result=tf_cube(2.0)    # New trace

x=2.0


In [200]:
result=tf_cube(3)      # New trace

x=3


In [201]:
result=tf_cube(tf.constant(2))     # New trace

x=Tensor("x:0", shape=(), dtype=int32)


In [202]:
result=tf_cube(tf.constant(4))     # used above graph ,no new trace

In [203]:
result=tf_cube(tf.constant([3,4]))   #   - shape changed - New trace

x=Tensor("x:0", shape=(2,), dtype=int32)


In [204]:
@tf.function(input_signature=[tf.TensorSpec([None,28,28],tf.float32)])
def shrink(images):
    print("Tracing",images)
    return images[:,::2,::2]
    

In [205]:
tf.keras.utils.set_random_seed(42)

In [206]:
img_batch1=tf.random.uniform(shape=[100,28,28])
img_batch2=tf.random.uniform(shape=[50,28,28])

preprocessed_images=shrink(img_batch1)
preprocessed_images=shrink(img_batch2)


Tracing Tensor("images:0", shape=(None, 28, 28), dtype=float32)


In [207]:
img_batch3=tf.random.uniform(shape=[50,30,30])  

try:
    preprocessed_images=shrink(img_batch3)
except TypeError as ex:
    print(ex)

Binding inputs to tf.function failed due to `Can not cast TensorSpec(shape=(50, 30, 30), dtype=tf.float32, name=None) to TensorSpec(shape=(None, 28, 28), dtype=tf.float32, name=None)`. Received args: (<tf.Tensor: shape=(50, 30, 30), dtype=float32, numpy=
array([[[7.41367817e-01, 6.28546238e-01, 1.73846483e-02, ...,
         1.01655841e-01, 1.94088340e-01, 2.78967142e-01],
        [3.95126343e-01, 1.22352123e-01, 3.84123683e-01, ...,
         2.89542437e-01, 5.49117088e-01, 5.06234169e-02],
        [1.92818403e-01, 4.54173088e-01, 2.18891740e-01, ...,
         5.14430046e-01, 6.94438338e-01, 3.70806217e-01],
        ...,
        [9.27087307e-01, 4.80402470e-01, 3.87802839e-01, ...,
         2.91818857e-01, 4.41177011e-01, 9.56274986e-01],
        [8.18418503e-01, 6.40728354e-01, 4.89600539e-01, ...,
         4.22110081e-01, 9.28475022e-01, 6.12375259e-01],
        [3.44055891e-02, 7.23996878e-01, 8.62124801e-01, ...,
         2.81303883e-01, 6.39876842e-01, 9.98726487e-01]],

       [[1

### Using Autograph to Capture Control Flow

In [209]:
@tf.function
def add_10(x):
    for i in range(10):
        x+=1
    return x

In [210]:
add_10(tf.constant(2.))

<tf.Tensor: shape=(), dtype=float32, numpy=12.0>

In [211]:
add_10.get_concrete_function(tf.constant(2.)).graph.get_operations()

[<tf.Operation 'x' type=Placeholder>,
 <tf.Operation 'add/y' type=Const>,
 <tf.Operation 'add' type=AddV2>,
 <tf.Operation 'add_1/y' type=Const>,
 <tf.Operation 'add_1' type=AddV2>,
 <tf.Operation 'add_2/y' type=Const>,
 <tf.Operation 'add_2' type=AddV2>,
 <tf.Operation 'add_3/y' type=Const>,
 <tf.Operation 'add_3' type=AddV2>,
 <tf.Operation 'add_4/y' type=Const>,
 <tf.Operation 'add_4' type=AddV2>,
 <tf.Operation 'add_5/y' type=Const>,
 <tf.Operation 'add_5' type=AddV2>,
 <tf.Operation 'add_6/y' type=Const>,
 <tf.Operation 'add_6' type=AddV2>,
 <tf.Operation 'add_7/y' type=Const>,
 <tf.Operation 'add_7' type=AddV2>,
 <tf.Operation 'add_8/y' type=Const>,
 <tf.Operation 'add_8' type=AddV2>,
 <tf.Operation 'add_9/y' type=Const>,
 <tf.Operation 'add_9' type=AddV2>,
 <tf.Operation 'Identity' type=Identity>]

In [212]:
@tf.function
def add_10(x):
    condition=lambda i,x:tf.less(i,10)
    body=lambda i,x:(tf.add(i,1),tf.add(x,1))
    final_i,final_x=tf.while_loop(condition,body,[tf.constant(0),x])
    return final_x

In [213]:
add_10(tf.constant(2.))

<tf.Tensor: shape=(), dtype=float32, numpy=12.0>

In [214]:
add_10.get_concrete_function(tf.constant(2.)).graph.get_operations()

[<tf.Operation 'x' type=Placeholder>,
 <tf.Operation 'Const' type=Const>,
 <tf.Operation 'while/maximum_iterations' type=Const>,
 <tf.Operation 'while/loop_counter' type=Const>,
 <tf.Operation 'while' type=StatelessWhile>,
 <tf.Operation 'Identity' type=Identity>]

In [215]:
@tf.function
def add_10(x):
    for i in tf.range(10):
        x=x+1
    return x

In [216]:
add_10.get_concrete_function(tf.constant(2.)).graph.get_operations()

[<tf.Operation 'x' type=Placeholder>,
 <tf.Operation 'range/start' type=Const>,
 <tf.Operation 'range/limit' type=Const>,
 <tf.Operation 'range/delta' type=Const>,
 <tf.Operation 'range' type=Range>,
 <tf.Operation 'sub' type=Sub>,
 <tf.Operation 'floordiv' type=FloorDiv>,
 <tf.Operation 'mod' type=FloorMod>,
 <tf.Operation 'zeros_like' type=Const>,
 <tf.Operation 'NotEqual' type=NotEqual>,
 <tf.Operation 'Cast' type=Cast>,
 <tf.Operation 'add' type=AddV2>,
 <tf.Operation 'zeros_like_1' type=Const>,
 <tf.Operation 'Maximum' type=Maximum>,
 <tf.Operation 'while/maximum_iterations' type=Const>,
 <tf.Operation 'while/loop_counter' type=Const>,
 <tf.Operation 'while' type=StatelessWhile>,
 <tf.Operation 'Identity' type=Identity>]

### Handling Variables and other Resources in TF functions

In [218]:
counter=tf.Variable(0)

@tf.function
def increment(counter,c=1):
    return counter.assign_add(c)
    
increment(counter)
increment(counter)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [219]:
function_def=increment.get_concrete_function(counter).function_def

In [220]:
function_def.signature.input_arg[0]

name: "counter"
type: DT_RESOURCE

In [221]:
counter=tf.Variable(0)

@tf.function
def increment(c=1):
    return counter.assign_add(c)

increment()
increment()

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [222]:
function_def=increment.get_concrete_function().function_def

In [223]:
function_def.signature.input_arg[0]

name: "assignaddvariableop_resource"
type: DT_RESOURCE

In [224]:
class Counter:
    def __init__(self):
        self.counter=tf.Variable(0)

    @tf.function
    def increment(self,c=1):
        return self.counter.assign_add(c)
        

In [225]:
c=Counter()
c.increment()
c.increment()

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [226]:
@tf.function
def add_10(x):
    for i in tf.range(10):
        x+=1
    return x


In [227]:
print(tf.autograph.to_code(add_10.python_function))

def tf__add(x):
    with ag__.FunctionScope('add_10', 'fscope', ag__.ConversionOptions(recursive=True, user_requested=True, optional_features=(), internal_convert_user_code=True)) as fscope:
        do_return = False
        retval_ = ag__.UndefinedReturnValue()

        def get_state():
            return (x,)

        def set_state(vars_):
            nonlocal x
            x, = vars_

        def loop_body(itr):
            nonlocal x
            i = itr
            x = ag__.ld(x)
            x += 1
        i = ag__.Undefined('i')
        ag__.for_stmt(ag__.converted_call(ag__.ld(tf).range, (10,), None, fscope), None, loop_body, get_state, set_state, ('x',), {'iterate_names': 'i'})
        try:
            do_return = True
            retval_ = ag__.ld(x)
        except:
            do_return = False
            raise
        return fscope.ret(retval_, do_return)



In [228]:
def display_tf_code(func):
    from IPython.display import display, Markdown
    if hasattr(func, "python_function"):
        func = func.python_function
    code = tf.autograph.to_code(func)
    display(Markdown(f'```python\n{code}\n```'))

In [229]:
display_tf_code(add_10)

```python
def tf__add(x):
    with ag__.FunctionScope('add_10', 'fscope', ag__.ConversionOptions(recursive=True, user_requested=True, optional_features=(), internal_convert_user_code=True)) as fscope:
        do_return = False
        retval_ = ag__.UndefinedReturnValue()

        def get_state():
            return (x,)

        def set_state(vars_):
            nonlocal x
            x, = vars_

        def loop_body(itr):
            nonlocal x
            i = itr
            x = ag__.ld(x)
            x += 1
        i = ag__.Undefined('i')
        ag__.for_stmt(ag__.converted_call(ag__.ld(tf).range, (10,), None, fscope), None, loop_body, get_state, set_state, ('x',), {'iterate_names': 'i'})
        try:
            do_return = True
            retval_ = ag__.ld(x)
        except:
            do_return = False
            raise
        return fscope.ret(retval_, do_return)

```

### Using TF function with tf.keras

In [231]:
#Custom loss function

def my_mse(y_true,y_pred):
    print("Tracing Loss my_mse()")
    return tf.reduce_mean(tf.square(y_pred-y_true))

In [232]:
#Custom metric function

def my_mae(y_true,y_pred):
    print("Tracing Metric my_mae()")
    return tf.reduce_mean(tf.abs(y_pred-y_true))

In [233]:
tf.keras.utils.set_random_seed(42)

In [234]:
#Custom Layer

class MyDense(tf.keras.layers.Layer):
    def __init__(self,units,activation=None,**kwargs):
        super().__init__(**kwargs)
        self.units=units
        self.activation=tf.keras.activations.get(activation)

    def build(self,input_shape):
        self.kernel=self.add_weight(name="kernel",
                                   shape=[input_shape[-1],self.units],
                                   initializer="he_normal",
                                   trainable=True)
        self.biases=self.add_weight(name="bias",
                                  shape=[self.units],
                                  initializer="zeros",
                                  trainable=True)

    def call(self,X):
        print("Tracing MyDense.call()")
        return self.activation(X@self.kernel+self.biases)
        

In [235]:
tf.keras.utils.set_random_seed(42)

In [236]:
## Custom Model

class MyModel(tf.keras.Model):
    def __init__(self,**kwargs):
        super().__init__(**kwargs)
        self.hidden1=MyDense(30,activation="relu")
        self.hidden2=MyDense(30,activation="relu")
        self.output_=MyDense(1)

    def call(self,input):
        print("Tracing MyModel.call()")
        hidden1=self.hidden1(input)
        hidden2=self.hidden2(hidden1)
        concat=tf.keras.layers.concatenate([input,hidden2])
        output=self.output_(concat)
        return output

In [237]:
model=MyModel()

In [238]:
model.compile(loss=my_mse,optimizer="adam",metrics=[my_mae])

In [239]:
model.fit(X_train_scaled,y_train,
         epochs=3,
         validation_data=(X_valid_scaled,y_valid))

Epoch 1/3
Tracing MyModel.call()
Tracing MyDense.call()
Tracing MyDense.call()
Tracing MyDense.call()
Tracing MyModel.call()
Tracing MyDense.call()
Tracing MyDense.call()
Tracing MyDense.call()
Tracing Loss my_mse()
Tracing Metric my_mae()
Tracing MyModel.call()
Tracing MyDense.call()
Tracing MyDense.call()
Tracing MyDense.call()
Tracing Loss my_mse()
Tracing Metric my_mae()
Tracing MyModel.call()━━━━━━━━━━━━━━━━━━━ 0s 400us/step - loss: 3.9819 - my_mae: 1.4569   
Tracing MyDense.call()
Tracing MyDense.call()
Tracing MyDense.call()
Tracing Loss my_mse()
Tracing Metric my_mae()
363/363 ━━━━━━━━━━━━━━━━━━━━ 1s 684us/step - loss: 3.3024 - my_mae: 1.2883 - val_loss: 0.6076 - val_my_mae: 0.5603
Epoch 2/3
363/363 ━━━━━━━━━━━━━━━━━━━━ 0s 550us/step - loss: 0.6214 - my_mae: 0.5698 - val_loss: 0.4603 - val_my_mae: 0.4899
Epoch 3/3
363/363 ━━━━━━━━━━━━━━━━━━━━ 0s 546us/step - loss: 0.5009 - my_mae: 0.5110 - val_loss: 0.4180 - val_my_mae: 0.4632


In [240]:
tf.keras.utils.set_random_seed(42)

In [241]:
model=MyModel()

In [242]:
model.compile(loss=my_mse,optimizer="adam",metrics=[my_mae],run_eagerly=True)

In [243]:
model.fit(X_train_scaled[:70],y_train[:70],
         epochs=3,
         validation_data=(X_valid_scaled[:70],y_valid[:70]))

Epoch 1/3
Tracing MyModel.call()
Tracing MyDense.call()
Tracing MyDense.call()
Tracing MyDense.call()
Tracing MyModel.call()
Tracing MyDense.call()
Tracing MyDense.call()
Tracing MyDense.call()
Tracing Loss my_mse()
Tracing Metric my_mae()
Tracing MyModel.call()━━━━━━━━━━━━━━━ 0s 55ms/step - loss: 11.6385 - my_mae: 2.8594
Tracing MyDense.call()
Tracing MyDense.call()
Tracing MyDense.call()
Tracing Loss my_mse()
Tracing Metric my_mae()
Tracing MyModel.call()
Tracing MyDense.call()
Tracing MyDense.call()
Tracing MyDense.call()
Tracing Loss my_mse()
Tracing Metric my_mae()
Tracing MyModel.call()
Tracing MyDense.call()
Tracing MyDense.call()
Tracing MyDense.call()
Tracing Loss my_mse()
Tracing Metric my_mae()
Tracing MyModel.call()
Tracing MyDense.call()
Tracing MyDense.call()
Tracing MyDense.call()
Tracing Loss my_mse()
Tracing Metric my_mae()
Tracing MyModel.call()
Tracing MyDense.call()
Tracing MyDense.call()
Tracing MyDense.call()
Tracing Loss my_mse()
Tracing Metric my_mae()
3/3 ━━━━━