# Using Tensorflow as Numpy

## Tensors and Operations

#### Tensors

In [5]:
import tensorflow as tf

t=tf.constant([[1,2,3],[4,5,6]])
t

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [6]:
t.shape

TensorShape([2, 3])

In [7]:
t.dtype

tf.int32

In [8]:
t.numpy()

array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)

In [9]:
t[:,:2]

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [4, 5]], dtype=int32)>

In [10]:
t[...,2,tf.newaxis]

<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[3],
       [6]], dtype=int32)>

#### ops

In [12]:
t+10

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[11, 12, 13],
       [14, 15, 16]], dtype=int32)>

In [13]:
tf.square(t)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 1,  4,  9],
       [16, 25, 36]], dtype=int32)>

In [14]:
t @ tf.transpose(t)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[14, 32],
       [32, 77]], dtype=int32)>

In [15]:
tf.constant(3)

<tf.Tensor: shape=(), dtype=int32, numpy=3>

#### Keras low level API

In [17]:
K=tf.keras.backend

K.square(K.transpose(t)) + 10

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[11, 26],
       [14, 35],
       [19, 46]], dtype=int32)>

In [18]:
tf.square(tf.transpose(t)) + 10

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[11, 26],
       [14, 35],
       [19, 46]], dtype=int32)>

#### Tensors and Numpy

In [20]:
tf.reduce_sum([1,2,4])


<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [21]:
import numpy as np

a=np.array([1.,2.,3.,4.])
tf.constant(a,dtype=tf.float32)

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([1., 2., 3., 4.], dtype=float32)>

In [22]:
np.array(t)

array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)

In [23]:
tf.square(a)

<tf.Tensor: shape=(4,), dtype=float64, numpy=array([ 1.,  4.,  9., 16.])>

In [24]:
np.square(t)

array([[ 1,  4,  9],
       [16, 25, 36]], dtype=int32)

#### Type conversions

In [26]:
try:
    tf.constant(2.0)+tf.constant(10)
except tf.errors.InvalidArgumentError as ex:
    print(ex)



cannot compute AddV2 as input #1(zero-based) was expected to be a float tensor but is a int32 tensor [Op:AddV2] name: 


In [27]:
try:
    tf.constant(2.0) +tf.constant(10.0,dtype=tf.float64)
except tf.errors.InvalidArgumentError as ex:
    print(ex)

cannot compute AddV2 as input #1(zero-based) was expected to be a float tensor but is a double tensor [Op:AddV2] name: 


In [28]:
t2=tf.constant(30,dtype=tf.float64)

tf.constant(5.0)+ tf.cast(t2,tf.float32)

<tf.Tensor: shape=(), dtype=float32, numpy=35.0>

#### Variables

In [30]:
v=tf.Variable([[1,2,3],[4,5,6]])
v

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [31]:
v.assign(v*2)

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=int32, numpy=
array([[ 2,  4,  6],
       [ 8, 10, 12]], dtype=int32)>

In [32]:
v[0,2].assign(33)

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=int32, numpy=
array([[ 2,  4, 33],
       [ 8, 10, 12]], dtype=int32)>

In [33]:
v[:,2].assign([0,9])

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=int32, numpy=
array([[ 2,  4,  0],
       [ 8, 10,  9]], dtype=int32)>

In [34]:
v.scatter_nd_update(
    indices=[[0,0],[1,2]],updates=[200,200]
)

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=int32, numpy=
array([[200,   4,   0],
       [  8,  10, 200]], dtype=int32)>

In [35]:
sparse_delta=tf.IndexedSlices(values=[[1,1,1],[2,2,2]],
                             indices=[1,0])
v.scatter_update(sparse_delta)


<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=int32, numpy=
array([[2, 2, 2],
       [1, 1, 1]], dtype=int32)>

In [36]:
try:
    v[1]=[2,2,2]
except TypeError as ex:
    print(ex)

'ResourceVariable' object does not support item assignment


#### Strings

In [38]:
tf.constant(b"hello")

<tf.Tensor: shape=(), dtype=string, numpy=b'hello'>

In [39]:
tf.constant("café")

<tf.Tensor: shape=(), dtype=string, numpy=b'caf\xc3\xa9'>

In [40]:
u=tf.constant([ord(c) for c in "café"])
u

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 99,  97, 102, 233], dtype=int32)>

In [41]:
b=tf.strings.unicode_encode(u,"UTF-8")
tf.strings.length(b, unit="UTF8_CHAR")

<tf.Tensor: shape=(), dtype=int32, numpy=4>

In [42]:
tf.strings.unicode_decode(b,"UTF-8")

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 99,  97, 102, 233], dtype=int32)>

In [43]:
p=tf.constant(["Café", "Coffee", "caffè", "चाय"])
tf.strings.length(p, unit="UTF8_CHAR")

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([4, 6, 5, 3], dtype=int32)>

In [44]:
r=tf.strings.unicode_decode(p,"UTF-8")
r

<tf.RaggedTensor [[67, 97, 102, 233], [67, 111, 102, 102, 101, 101],
 [99, 97, 102, 102, 232], [2330, 2366, 2351]]>

#### Ragged Tensors

In [46]:
r=tf.ragged.constant([[2,4,5,7],[6,7],[],[7,5,2]])
r

<tf.RaggedTensor [[2, 4, 5, 7], [6, 7], [], [7, 5, 2]]>

In [47]:
r.to_tensor()

<tf.Tensor: shape=(4, 4), dtype=int32, numpy=
array([[2, 4, 5, 7],
       [6, 7, 0, 0],
       [0, 0, 0, 0],
       [7, 5, 2, 0]], dtype=int32)>

# Customizing Models and Training Algorithms

## Custom Loss Function

In [50]:
def huber_fn(y_true,y_pred):
    error=y_true - y_pred
    is_small_error = tf.abs(error) < 1
    square_loss= tf.square(error)/2
    linear_loss= tf.abs(error) - 0.5
    return tf.where(is_small_error,square_loss,linear_loss)

In [51]:
from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

housing=fetch_california_housing()
X_train_full,X_test,y_train_full,y_test=train_test_split(housing.data,housing.target.reshape(-1,1),
                                                        random_state=42)
X_train,X_valid,y_train,y_valid=train_test_split(X_train_full,y_train_full,random_state=42)

input_shape=X_train.shape[1:]

scaler=StandardScaler()
X_train_scaled=scaler.fit_transform(X_train)
X_valid_scaled=scaler.transform(X_valid)
X_test_scaled=scaler.transform(X_test)

tf.random.set_seed(42)

model=tf.keras.Sequential([
    tf.keras.layers.InputLayer(shape=input_shape),
    tf.keras.layers.Dense(25,activation="relu",kernel_initializer="he_normal"),
    tf.keras.layers.Dense(1)
])


In [52]:
model.compile(loss=huber_fn,
             optimizer="nadam",
             metrics=["mae"])

model.fit(X_train_scaled,y_train,
         epochs=5,
         validation_data=(X_valid_scaled,y_valid))

Epoch 1/5
363/363 ━━━━━━━━━━━━━━━━━━━━ 1s 676us/step - loss: 1.1788 - mae: 1.5931 - val_loss: 0.3078 - val_mae: 0.6376
Epoch 2/5
363/363 ━━━━━━━━━━━━━━━━━━━━ 0s 514us/step - loss: 0.3048 - mae: 0.6248 - val_loss: 0.2297 - val_mae: 0.5284
Epoch 3/5
363/363 ━━━━━━━━━━━━━━━━━━━━ 0s 517us/step - loss: 0.2426 - mae: 0.5419 - val_loss: 0.1990 - val_mae: 0.4829
Epoch 4/5
363/363 ━━━━━━━━━━━━━━━━━━━━ 0s 514us/step - loss: 0.2126 - mae: 0.5011 - val_loss: 0.1826 - val_mae: 0.4600
Epoch 5/5
363/363 ━━━━━━━━━━━━━━━━━━━━ 0s 515us/step - loss: 0.1972 - mae: 0.4803 - val_loss: 0.1750 - val_mae: 0.4491


## Storing and Loading Models With Custom Objects

In [54]:
model.save("my_custom_loss_fn_model.keras")

In [55]:
model=tf.keras.models.load_model("my_custom_loss_fn_model.keras",
                                custom_objects={"huber_fn":huber_fn})

In [56]:
model.fit(X_train_scaled,y_train,
         epochs=4,
         validation_data=(X_valid_scaled,y_valid))

Epoch 1/4
363/363 ━━━━━━━━━━━━━━━━━━━━ 1s 676us/step - loss: 0.1884 - mae: 0.4689 - val_loss: 0.1708 - val_mae: 0.4426
Epoch 2/4
363/363 ━━━━━━━━━━━━━━━━━━━━ 0s 518us/step - loss: 0.1825 - mae: 0.4611 - val_loss: 0.1679 - val_mae: 0.4378
Epoch 3/4
363/363 ━━━━━━━━━━━━━━━━━━━━ 0s 518us/step - loss: 0.1780 - mae: 0.4545 - val_loss: 0.1660 - val_mae: 0.4347
Epoch 4/4
363/363 ━━━━━━━━━━━━━━━━━━━━ 0s 601us/step - loss: 0.1745 - mae: 0.4492 - val_loss: 0.1650 - val_mae: 0.4324


In [57]:
def create_huber(threshold=1.0):
    def huber_fn(y_true,y_pred):
        error= y_true-y_pred
        is_small_error= tf.abs(error)< threshold
        squared_loss= tf.square(error)/2
        linear_loss= threshold*tf.abs(error) - threshold**2 / 2
        return tf.where(is_small_error,squared_loss,linear_loss)
    return huber_fn

In [58]:
model.compile(loss=create_huber(1.8),optimizer="nadam",metrics=["mae"])

In [59]:
model.fit(X_train_scaled,y_train,
         epochs=4,
         validation_data=(X_valid_scaled,y_valid))

Epoch 1/4
363/363 ━━━━━━━━━━━━━━━━━━━━ 1s 678us/step - loss: 0.1909 - mae: 0.4475 - val_loss: 0.1742 - val_mae: 0.4258
Epoch 2/4
363/363 ━━━━━━━━━━━━━━━━━━━━ 0s 522us/step - loss: 0.1876 - mae: 0.4432 - val_loss: 0.1881 - val_mae: 0.4329
Epoch 3/4
363/363 ━━━━━━━━━━━━━━━━━━━━ 0s 520us/step - loss: 0.1855 - mae: 0.4405 - val_loss: 0.1711 - val_mae: 0.4215
Epoch 4/4
363/363 ━━━━━━━━━━━━━━━━━━━━ 0s 518us/step - loss: 0.1839 - mae: 0.4379 - val_loss: 0.1914 - val_mae: 0.4326


In [60]:
model.save("my_custom_loss_threshold_model.keras")

In [61]:
model=tf.keras.models.load_model("my_custom_loss_threshold_model.keras",
                                custom_objects={"huber_fn":create_huber(1.8)})

In [62]:
model.fit(X_train_scaled,y_train,
         epochs=2,
         validation_data=(X_valid_scaled,y_valid))

Epoch 1/2
363/363 ━━━━━━━━━━━━━━━━━━━━ 0s 677us/step - loss: 0.1824 - mae: 0.4360 - val_loss: 0.1779 - val_mae: 0.4227
Epoch 2/2
363/363 ━━━━━━━━━━━━━━━━━━━━ 0s 523us/step - loss: 0.1814 - mae: 0.4338 - val_loss: 0.1862 - val_mae: 0.4274


In [63]:
class HuberLoss(tf.keras.losses.Loss):
    def __init__(self,threshold=1.0,**kwargs):
        self.threshold=threshold
        super().__init__(**kwargs)
        
    def call(self,y_true,y_pred):
        error= y_true - y_pred
        is_small_error= tf.abs(error) < self.threshold
        square_loss= tf.square(error) /2
        linear_loss= self.threshold * tf.abs(error) - self.threshold**2 / 2
        return tf.where(is_small_error,square_loss,linear_loss)

    def get_config(self):
        base_config=super().get_config()
        return {**base_config,"threshold":self.threshold}

In [64]:
tf.random.set_seed(42)

model=tf.keras.Sequential([
    tf.keras.layers.InputLayer(shape=input_shape),
    tf.keras.layers.Dense(30,activation="relu",
                         kernel_initializer="he_normal"),
    tf.keras.layers.Dense(1)
])


In [65]:
model.compile(loss=HuberLoss(1.4),optimizer="nadam",metrics=["mae"])

In [66]:
model.fit(X_train_scaled,y_train,
         epochs=3,
         validation_data=(X_valid_scaled,y_valid))

Epoch 1/3
363/363 ━━━━━━━━━━━━━━━━━━━━ 1s 676us/step - loss: 1.4719 - mae: 1.5914 - val_loss: 0.3228 - val_mae: 0.6048
Epoch 2/3
363/363 ━━━━━━━━━━━━━━━━━━━━ 0s 519us/step - loss: 0.2970 - mae: 0.5812 - val_loss: 0.2360 - val_mae: 0.5063
Epoch 3/3
363/363 ━━━━━━━━━━━━━━━━━━━━ 0s 521us/step - loss: 0.2384 - mae: 0.5111 - val_loss: 0.2064 - val_mae: 0.4661


In [67]:
model.save("my_custom_loss_threshold_class_model.keras")

In [68]:
model=tf.keras.models.load_model("my_custom_loss_threshold_class_model.keras",
                                custom_objects={"HuberLoss":HuberLoss})

In [69]:
model.fit(X_train_scaled,y_train,
         epochs=3,
          validation_data=(X_valid_scaled,y_valid)
         )

Epoch 1/3
363/363 ━━━━━━━━━━━━━━━━━━━━ 0s 678us/step - loss: 0.2125 - mae: 0.4773 - val_loss: 0.1922 - val_mae: 0.4470
Epoch 2/3
363/363 ━━━━━━━━━━━━━━━━━━━━ 0s 518us/step - loss: 0.1997 - mae: 0.4606 - val_loss: 0.1819 - val_mae: 0.4358
Epoch 3/3
363/363 ━━━━━━━━━━━━━━━━━━━━ 0s 517us/step - loss: 0.1927 - mae: 0.4515 - val_loss: 0.1738 - val_mae: 0.4280


In [70]:
model.loss.threshold

1.4

## Other Custom Functions

In [72]:
def my_softplus(z):
    return tf.math.log(1+tf.exp(z))

def my_glorot_initializer(shape,dtype=tf.float32):
    stddev= tf.sqrt(2 / (shape[0] + shape[1]))
    return tf.random.normal(shape,stddev=stddev,dtype=dtype)

def my_l1_regu(weights):
    return 0.01 * tf.reduce_sum(tf.abs(weights))

def my_positive_weights(weights):
    return tf.where(weights<0. ,tf.zeros_like(weights),weights)

In [74]:
class MyL1Regularizer(tf.keras.regularizers.Regularizer):
    def __init__(self, factor):
        self.factor = factor

    def __call__(self, weights):
        return self.factor * tf.reduce_sum(tf.abs(weights))

    def get_config(self):
        return {"factor": self.factor}


In [86]:
class MyPositiveWeights(tf.keras.constraints.Constraint):
    def __init__(self):
        pass
    def __call__(self,weights):
        return tf.where(weights<0. ,tf.zeros_like(weights),weights)
    def get_config(self):
        return {}
    

In [96]:
tf.random.set_seed(42)

model=tf.keras.Sequential([
    tf.keras.layers.InputLayer(shape=input_shape),
    tf.keras.layers.Dense(30,activation=my_softplus,
                          kernel_initializer=my_glorot_initializer,
                          kernel_regularizer=MyL1Regularizer(factor=0.01),
                          kernel_constraint=MyPositiveWeights()
                           ),
                         
    tf.keras.layers.Dense(1)
])
model.summary()

Model: "sequential_10"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_20 (Dense)                │ (None, 30)             │           270 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_21 (Dense)                │ (None, 1)              │            31 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 301 (1.18 KB)

 Trainable params: 301 (1.18 KB)

 Non-trainable params: 0 (0.00 B)

In [100]:
model.compile(loss=HuberLoss(1.2),optimizer="nadam",metrics=["mae"])

In [104]:
history=model.fit(X_train_scaled,y_train,
                 epochs=4,
                 validation_data=(X_valid_scaled,y_valid))

Epoch 1/4
363/363 ━━━━━━━━━━━━━━━━━━━━ 0s 618us/step - loss: 0.3488 - mae: 0.6051 - val_loss: 0.3281 - val_mae: 0.5846
Epoch 2/4
363/363 ━━━━━━━━━━━━━━━━━━━━ 0s 549us/step - loss: 0.3416 - mae: 0.6026 - val_loss: 0.3221 - val_mae: 0.5804
Epoch 3/4
363/363 ━━━━━━━━━━━━━━━━━━━━ 0s 540us/step - loss: 0.3352 - mae: 0.5979 - val_loss: 0.3181 - val_mae: 0.5764
Epoch 4/4
363/363 ━━━━━━━━━━━━━━━━━━━━ 0s 544us/step - loss: 0.3295 - mae: 0.5922 - val_loss: 0.3164 - val_mae: 0.5725
